"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Int128(_message.Message):
    """The low 64 bits are stored in "low", and the high 64-bits (including the
    sign) are stored in "high".
    """

    DESCRIPTOR: _descriptor.Descriptor

    HIGH_FIELD_NUMBER: _builtins.int
    LOW_FIELD_NUMBER: _builtins.int
    high: _builtins.int
    low: _builtins.int
    def __init__(
        self,
        *,
        high: _builtins.int = ...,
        low: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["high", b"high", "low", b"low"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Int128: _TypeAlias = Int128  # noqa: Y015
