"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protobuf representing a flow problem on a graph. It supports several problem
types. Depending on the type, the message is interpreted differently as
explained under each type description below.

LINEAR_SUM_ASSIGNMENT: the algorithm computes the minimum-cost perfect
matching if there is one.
 - Arcs are assumed to be from a left node to a right node. In particular
   the id space of the left and right nodes can be the same. That is an arc
   from the left node 0 to the right node 0 will be coded as (0, 0).
 - If a perfect matching does not exist, the problem is not feasible.
 - Capacity and supply values are ignored.

MAX_FLOW: The algorithm computes the maximum flow under the arc capacity
constraints.
 - Only one source (with supply > 0) and one sink (with supply < 0), the
   supply values are not important. Only the signs are.
 - The costs are ignored.

MIN_COST_FLOW: the algorithm computes the flow of minimum cost. If a feasible
flow does not exist (in particular if the sum of supplies is not 0), the
problem is not feasible.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FlowArcProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAIL_FIELD_NUMBER: _builtins.int
    HEAD_FIELD_NUMBER: _builtins.int
    CAPACITY_FIELD_NUMBER: _builtins.int
    UNIT_COST_FIELD_NUMBER: _builtins.int
    tail: _builtins.int
    """A directed arc goes from a tail node to a head node.
    Node ids must be non-negative (>= 0).
    """
    head: _builtins.int
    capacity: _builtins.int
    """Capacity of the arc. Must be non-negative (>= 0). If the capacity is zero,
    it is equivalent to not including the arc in the FlowModelProto.
    """
    unit_cost: _builtins.int
    """Cost of this arc per unit of flow.
    Note that it can take any positive, negative or null value.
    """
    def __init__(
        self,
        *,
        tail: _builtins.int | None = ...,
        head: _builtins.int | None = ...,
        capacity: _builtins.int | None = ...,
        unit_cost: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capacity", b"capacity", "head", b"head", "tail", b"tail", "unit_cost", b"unit_cost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capacity", b"capacity", "head", b"head", "tail", b"tail", "unit_cost", b"unit_cost"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FlowArcProto: _TypeAlias = FlowArcProto  # noqa: Y015

@_typing.final
class FlowNodeProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SUPPLY_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    """The ids must be non-negative (>= 0). They should be dense for good
    performance. Note that it is not mandatory to include nodes with no supply
    in a FlowModelProto.
    """
    supply: _builtins.int
    """The supply can be positive or negative in which case it means demand.
    The sum of the supplies over all nodes must always be 0.
    """
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        supply: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "supply", b"supply"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "supply", b"supply"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FlowNodeProto: _TypeAlias = FlowNodeProto  # noqa: Y015

@_typing.final
class FlowModelProto(_message.Message):
    """Holds a flow problem, see NodeProto and ArcProto for more details."""

    DESCRIPTOR: _descriptor.Descriptor

    class _ProblemType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ProblemTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FlowModelProto._ProblemType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LINEAR_SUM_ASSIGNMENT: FlowModelProto._ProblemType.ValueType  # 0
        MAX_FLOW: FlowModelProto._ProblemType.ValueType  # 1
        MIN_COST_FLOW: FlowModelProto._ProblemType.ValueType  # 2

    class ProblemType(_ProblemType, metaclass=_ProblemTypeEnumTypeWrapper):
        """The type of problem to solve."""

    LINEAR_SUM_ASSIGNMENT: FlowModelProto.ProblemType.ValueType  # 0
    MAX_FLOW: FlowModelProto.ProblemType.ValueType  # 1
    MIN_COST_FLOW: FlowModelProto.ProblemType.ValueType  # 2

    NODES_FIELD_NUMBER: _builtins.int
    ARCS_FIELD_NUMBER: _builtins.int
    PROBLEM_TYPE_FIELD_NUMBER: _builtins.int
    problem_type: Global___FlowModelProto.ProblemType.ValueType
    @_builtins.property
    def nodes(self) -> _containers.RepeatedCompositeFieldContainer[Global___FlowNodeProto]: ...
    @_builtins.property
    def arcs(self) -> _containers.RepeatedCompositeFieldContainer[Global___FlowArcProto]: ...
    def __init__(
        self,
        *,
        nodes: _abc.Iterable[Global___FlowNodeProto] | None = ...,
        arcs: _abc.Iterable[Global___FlowArcProto] | None = ...,
        problem_type: Global___FlowModelProto.ProblemType.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["problem_type", b"problem_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arcs", b"arcs", "nodes", b"nodes", "problem_type", b"problem_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FlowModelProto: _TypeAlias = FlowModelProto  # noqa: Y015
