"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Proto messages specific to Gurobi.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GurobiInitializerProto(_message.Message):
    """Parameters used to initialize the Gurobi solver."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ISVKey(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        APPLICATION_NAME_FIELD_NUMBER: _builtins.int
        EXPIRATION_FIELD_NUMBER: _builtins.int
        KEY_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        application_name: _builtins.str
        expiration: _builtins.int
        key: _builtins.str
        def __init__(
            self,
            *,
            name: _builtins.str = ...,
            application_name: _builtins.str = ...,
            expiration: _builtins.int = ...,
            key: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["application_name", b"application_name", "expiration", b"expiration", "key", b"key", "name", b"name"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ISV_KEY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def isv_key(self) -> Global___GurobiInitializerProto.ISVKey:
        """An optional ISV key to use.

        See http://www.gurobi.com/products/licensing-pricing/isv-program.
        """

    def __init__(
        self,
        *,
        isv_key: Global___GurobiInitializerProto.ISVKey | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["isv_key", b"isv_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["isv_key", b"isv_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GurobiInitializerProto: _TypeAlias = GurobiInitializerProto  # noqa: Y015

@_typing.final
class GurobiParametersProto(_message.Message):
    """Gurobi specific parameters for solving. See
      https://www.gurobi.com/documentation/9.1/refman/parameters.html
    for a list of possible parameters.

    Example text proto to set the Barrier Iteration Limit:
      parameters : [{name: "BarIterLimit" value: "10}]

    With Gurobi, the order that parameters are applied can have an impact in rare
    situations. Parameters are applied in the following order:
     * LogToConsole is set from CommonSolveParameters.enable_output.
     * Any common parameters not overwritten by GurobiParameters.
     * param_values in iteration order (insertion order).
    We set LogToConsole first because setting other parameters can generate
    output.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Parameter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            name: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PARAMETERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___GurobiParametersProto.Parameter]: ...
    def __init__(
        self,
        *,
        parameters: _abc.Iterable[Global___GurobiParametersProto.Parameter] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["parameters", b"parameters"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GurobiParametersProto: _TypeAlias = GurobiParametersProto  # noqa: Y015
