"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HighsOptionsProto(_message.Message):
    """The options exposed by HiGHS. Use at your own risk, these are completely
    undocumented.

    Option names are given as strings in HighsOptions.h, see:
    https://github.com/ERGO-Code/HiGHS/blob/7421e44b09563f637dc6422ea461a8832b29e543/src/lp_data/HighsOptions.h
    Each member of HighsOptionsStruct has a corresponding OptionRecord with a
    string name (that appears to match the field name), use these as keys below.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StringOptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DoubleOptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.float
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.float = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class IntOptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BoolOptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bool
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STRING_OPTIONS_FIELD_NUMBER: _builtins.int
    DOUBLE_OPTIONS_FIELD_NUMBER: _builtins.int
    INT_OPTIONS_FIELD_NUMBER: _builtins.int
    BOOL_OPTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def string_options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Example keys: "presolve", "solver", "parallel" """

    @_builtins.property
    def double_options(self) -> _containers.ScalarMap[_builtins.str, _builtins.float]:
        """Example keys: "time_limit", "primal_feasibility_tolerance" """

    @_builtins.property
    def int_options(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]:
        """Example keys: "random_seed", "simplex_strategy" """

    @_builtins.property
    def bool_options(self) -> _containers.ScalarMap[_builtins.str, _builtins.bool]:
        """Example keys: "log_to_console", "allow_unbounded_or_infeasible" """

    def __init__(
        self,
        *,
        string_options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        double_options: _abc.Mapping[_builtins.str, _builtins.float] | None = ...,
        int_options: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
        bool_options: _abc.Mapping[_builtins.str, _builtins.bool] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_options", b"bool_options", "double_options", b"double_options", "int_options", b"int_options", "string_options", b"string_options"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HighsOptionsProto: _TypeAlias = HighsOptionsProto  # noqa: Y015
