"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OsqpSettingsProto(_message.Message):
    """This proto mirrors the fields of OsqpSettings in
    osqp_cpp/include/osqp++.h, which in turn (nearly) mirrors the
    fields of OSQPSettings in osqp/include/types.h. See also
    https://osqp.org/docs/interfaces/solver_settings.html for documentation and
    default values. This proto must be kept in sync with logic in osqp_solver.cc.
    LINT.IfChange
    """

    DESCRIPTOR: _descriptor.Descriptor

    RHO_FIELD_NUMBER: _builtins.int
    SIGMA_FIELD_NUMBER: _builtins.int
    SCALING_FIELD_NUMBER: _builtins.int
    ADAPTIVE_RHO_FIELD_NUMBER: _builtins.int
    ADAPTIVE_RHO_INTERVAL_FIELD_NUMBER: _builtins.int
    ADAPTIVE_RHO_TOLERANCE_FIELD_NUMBER: _builtins.int
    ADAPTIVE_RHO_FRACTION_FIELD_NUMBER: _builtins.int
    MAX_ITER_FIELD_NUMBER: _builtins.int
    EPS_ABS_FIELD_NUMBER: _builtins.int
    EPS_REL_FIELD_NUMBER: _builtins.int
    EPS_PRIM_INF_FIELD_NUMBER: _builtins.int
    EPS_DUAL_INF_FIELD_NUMBER: _builtins.int
    ALPHA_FIELD_NUMBER: _builtins.int
    DELTA_FIELD_NUMBER: _builtins.int
    POLISH_FIELD_NUMBER: _builtins.int
    POLISH_REFINE_ITER_FIELD_NUMBER: _builtins.int
    VERBOSE_FIELD_NUMBER: _builtins.int
    SCALED_TERMINATION_FIELD_NUMBER: _builtins.int
    CHECK_TERMINATION_FIELD_NUMBER: _builtins.int
    WARM_START_FIELD_NUMBER: _builtins.int
    TIME_LIMIT_FIELD_NUMBER: _builtins.int
    rho: _builtins.float
    """ADMM rho step. Must be > 0."""
    sigma: _builtins.float
    """ADMM sigma step. Must be > 0."""
    scaling: _builtins.int
    """Number of heuristic scaling iterations. Must be >= 0."""
    adaptive_rho: _builtins.bool
    """Is rho step size adaptive?"""
    adaptive_rho_interval: _builtins.int
    """Number of iterations between rho adaptations; if 0, then automatically
    selected. Must be >= 0.
    """
    adaptive_rho_tolerance: _builtins.float
    """Tolerance X for adapting rho: The new value must be X times larger or 1/X
    times smaller than the current value. Must be >= 1.
    """
    adaptive_rho_fraction: _builtins.float
    """In automatic mode (adaptive_rho_interval = 0), what fraction of setup time
    is spent on selecting rho. Must be >= 0.
    """
    max_iter: _builtins.int
    """Maximum number of iterations. Must be > 0."""
    eps_abs: _builtins.float
    """Absolute error tolerance for convergence. Must be >= 0."""
    eps_rel: _builtins.float
    """Relative error tolerance for convergence. Must be >= 0."""
    eps_prim_inf: _builtins.float
    """Absolute error tolerance for primal infeasibility. Must be >= 0."""
    eps_dual_inf: _builtins.float
    """Relative error tolerance for dual infeasibility. Must be >= 0."""
    alpha: _builtins.float
    """ADMM overrelaxation parameter. Must be > 0 and < 2."""
    delta: _builtins.float
    """Polishing regularization parameter. Must be > 0."""
    polish: _builtins.bool
    """Perform polishing?"""
    polish_refine_iter: _builtins.int
    """Number of refinement iterations in polishing. Must be > 0."""
    verbose: _builtins.bool
    """Print solver output?"""
    scaled_termination: _builtins.bool
    """Use scaled termination criteria?"""
    check_termination: _builtins.int
    """Interval for checking termination. If 0 or unset, termination checking is
    disabled. Must be >= 0.
    """
    warm_start: _builtins.bool
    """Perform warm starting?."""
    time_limit: _builtins.float
    """Run time limit in seconds. If 0 or unset, then no time limit. Must be >= 0."""
    def __init__(
        self,
        *,
        rho: _builtins.float | None = ...,
        sigma: _builtins.float | None = ...,
        scaling: _builtins.int | None = ...,
        adaptive_rho: _builtins.bool | None = ...,
        adaptive_rho_interval: _builtins.int | None = ...,
        adaptive_rho_tolerance: _builtins.float | None = ...,
        adaptive_rho_fraction: _builtins.float | None = ...,
        max_iter: _builtins.int | None = ...,
        eps_abs: _builtins.float | None = ...,
        eps_rel: _builtins.float | None = ...,
        eps_prim_inf: _builtins.float | None = ...,
        eps_dual_inf: _builtins.float | None = ...,
        alpha: _builtins.float | None = ...,
        delta: _builtins.float | None = ...,
        polish: _builtins.bool | None = ...,
        polish_refine_iter: _builtins.int | None = ...,
        verbose: _builtins.bool | None = ...,
        scaled_termination: _builtins.bool | None = ...,
        check_termination: _builtins.int | None = ...,
        warm_start: _builtins.bool | None = ...,
        time_limit: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_adaptive_rho", b"_adaptive_rho", "_adaptive_rho_fraction", b"_adaptive_rho_fraction", "_adaptive_rho_interval", b"_adaptive_rho_interval", "_adaptive_rho_tolerance", b"_adaptive_rho_tolerance", "_alpha", b"_alpha", "_check_termination", b"_check_termination", "_delta", b"_delta", "_eps_abs", b"_eps_abs", "_eps_dual_inf", b"_eps_dual_inf", "_eps_prim_inf", b"_eps_prim_inf", "_eps_rel", b"_eps_rel", "_max_iter", b"_max_iter", "_polish", b"_polish", "_polish_refine_iter", b"_polish_refine_iter", "_rho", b"_rho", "_scaled_termination", b"_scaled_termination", "_scaling", b"_scaling", "_sigma", b"_sigma", "_time_limit", b"_time_limit", "_verbose", b"_verbose", "_warm_start", b"_warm_start", "adaptive_rho", b"adaptive_rho", "adaptive_rho_fraction", b"adaptive_rho_fraction", "adaptive_rho_interval", b"adaptive_rho_interval", "adaptive_rho_tolerance", b"adaptive_rho_tolerance", "alpha", b"alpha", "check_termination", b"check_termination", "delta", b"delta", "eps_abs", b"eps_abs", "eps_dual_inf", b"eps_dual_inf", "eps_prim_inf", b"eps_prim_inf", "eps_rel", b"eps_rel", "max_iter", b"max_iter", "polish", b"polish", "polish_refine_iter", b"polish_refine_iter", "rho", b"rho", "scaled_termination", b"scaled_termination", "scaling", b"scaling", "sigma", b"sigma", "time_limit", b"time_limit", "verbose", b"verbose", "warm_start", b"warm_start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_adaptive_rho", b"_adaptive_rho", "_adaptive_rho_fraction", b"_adaptive_rho_fraction", "_adaptive_rho_interval", b"_adaptive_rho_interval", "_adaptive_rho_tolerance", b"_adaptive_rho_tolerance", "_alpha", b"_alpha", "_check_termination", b"_check_termination", "_delta", b"_delta", "_eps_abs", b"_eps_abs", "_eps_dual_inf", b"_eps_dual_inf", "_eps_prim_inf", b"_eps_prim_inf", "_eps_rel", b"_eps_rel", "_max_iter", b"_max_iter", "_polish", b"_polish", "_polish_refine_iter", b"_polish_refine_iter", "_rho", b"_rho", "_scaled_termination", b"_scaled_termination", "_scaling", b"_scaling", "_sigma", b"_sigma", "_time_limit", b"_time_limit", "_verbose", b"_verbose", "_warm_start", b"_warm_start", "adaptive_rho", b"adaptive_rho", "adaptive_rho_fraction", b"adaptive_rho_fraction", "adaptive_rho_interval", b"adaptive_rho_interval", "adaptive_rho_tolerance", b"adaptive_rho_tolerance", "alpha", b"alpha", "check_termination", b"check_termination", "delta", b"delta", "eps_abs", b"eps_abs", "eps_dual_inf", b"eps_dual_inf", "eps_prim_inf", b"eps_prim_inf", "eps_rel", b"eps_rel", "max_iter", b"max_iter", "polish", b"polish", "polish_refine_iter", b"polish_refine_iter", "rho", b"rho", "scaled_termination", b"scaled_termination", "scaling", b"scaling", "sigma", b"sigma", "time_limit", b"time_limit", "verbose", b"verbose", "warm_start", b"warm_start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__adaptive_rho: _TypeAlias = _typing.Literal["adaptive_rho"]  # noqa: Y015
    _WhichOneofArgType__adaptive_rho: _TypeAlias = _typing.Literal["_adaptive_rho", b"_adaptive_rho"]  # noqa: Y015
    _WhichOneofReturnType__adaptive_rho_fraction: _TypeAlias = _typing.Literal["adaptive_rho_fraction"]  # noqa: Y015
    _WhichOneofArgType__adaptive_rho_fraction: _TypeAlias = _typing.Literal["_adaptive_rho_fraction", b"_adaptive_rho_fraction"]  # noqa: Y015
    _WhichOneofReturnType__adaptive_rho_interval: _TypeAlias = _typing.Literal["adaptive_rho_interval"]  # noqa: Y015
    _WhichOneofArgType__adaptive_rho_interval: _TypeAlias = _typing.Literal["_adaptive_rho_interval", b"_adaptive_rho_interval"]  # noqa: Y015
    _WhichOneofReturnType__adaptive_rho_tolerance: _TypeAlias = _typing.Literal["adaptive_rho_tolerance"]  # noqa: Y015
    _WhichOneofArgType__adaptive_rho_tolerance: _TypeAlias = _typing.Literal["_adaptive_rho_tolerance", b"_adaptive_rho_tolerance"]  # noqa: Y015
    _WhichOneofReturnType__alpha: _TypeAlias = _typing.Literal["alpha"]  # noqa: Y015
    _WhichOneofArgType__alpha: _TypeAlias = _typing.Literal["_alpha", b"_alpha"]  # noqa: Y015
    _WhichOneofReturnType__check_termination: _TypeAlias = _typing.Literal["check_termination"]  # noqa: Y015
    _WhichOneofArgType__check_termination: _TypeAlias = _typing.Literal["_check_termination", b"_check_termination"]  # noqa: Y015
    _WhichOneofReturnType__delta: _TypeAlias = _typing.Literal["delta"]  # noqa: Y015
    _WhichOneofArgType__delta: _TypeAlias = _typing.Literal["_delta", b"_delta"]  # noqa: Y015
    _WhichOneofReturnType__eps_abs: _TypeAlias = _typing.Literal["eps_abs"]  # noqa: Y015
    _WhichOneofArgType__eps_abs: _TypeAlias = _typing.Literal["_eps_abs", b"_eps_abs"]  # noqa: Y015
    _WhichOneofReturnType__eps_dual_inf: _TypeAlias = _typing.Literal["eps_dual_inf"]  # noqa: Y015
    _WhichOneofArgType__eps_dual_inf: _TypeAlias = _typing.Literal["_eps_dual_inf", b"_eps_dual_inf"]  # noqa: Y015
    _WhichOneofReturnType__eps_prim_inf: _TypeAlias = _typing.Literal["eps_prim_inf"]  # noqa: Y015
    _WhichOneofArgType__eps_prim_inf: _TypeAlias = _typing.Literal["_eps_prim_inf", b"_eps_prim_inf"]  # noqa: Y015
    _WhichOneofReturnType__eps_rel: _TypeAlias = _typing.Literal["eps_rel"]  # noqa: Y015
    _WhichOneofArgType__eps_rel: _TypeAlias = _typing.Literal["_eps_rel", b"_eps_rel"]  # noqa: Y015
    _WhichOneofReturnType__max_iter: _TypeAlias = _typing.Literal["max_iter"]  # noqa: Y015
    _WhichOneofArgType__max_iter: _TypeAlias = _typing.Literal["_max_iter", b"_max_iter"]  # noqa: Y015
    _WhichOneofReturnType__polish: _TypeAlias = _typing.Literal["polish"]  # noqa: Y015
    _WhichOneofArgType__polish: _TypeAlias = _typing.Literal["_polish", b"_polish"]  # noqa: Y015
    _WhichOneofReturnType__polish_refine_iter: _TypeAlias = _typing.Literal["polish_refine_iter"]  # noqa: Y015
    _WhichOneofArgType__polish_refine_iter: _TypeAlias = _typing.Literal["_polish_refine_iter", b"_polish_refine_iter"]  # noqa: Y015
    _WhichOneofReturnType__rho: _TypeAlias = _typing.Literal["rho"]  # noqa: Y015
    _WhichOneofArgType__rho: _TypeAlias = _typing.Literal["_rho", b"_rho"]  # noqa: Y015
    _WhichOneofReturnType__scaled_termination: _TypeAlias = _typing.Literal["scaled_termination"]  # noqa: Y015
    _WhichOneofArgType__scaled_termination: _TypeAlias = _typing.Literal["_scaled_termination", b"_scaled_termination"]  # noqa: Y015
    _WhichOneofReturnType__scaling: _TypeAlias = _typing.Literal["scaling"]  # noqa: Y015
    _WhichOneofArgType__scaling: _TypeAlias = _typing.Literal["_scaling", b"_scaling"]  # noqa: Y015
    _WhichOneofReturnType__sigma: _TypeAlias = _typing.Literal["sigma"]  # noqa: Y015
    _WhichOneofArgType__sigma: _TypeAlias = _typing.Literal["_sigma", b"_sigma"]  # noqa: Y015
    _WhichOneofReturnType__time_limit: _TypeAlias = _typing.Literal["time_limit"]  # noqa: Y015
    _WhichOneofArgType__time_limit: _TypeAlias = _typing.Literal["_time_limit", b"_time_limit"]  # noqa: Y015
    _WhichOneofReturnType__verbose: _TypeAlias = _typing.Literal["verbose"]  # noqa: Y015
    _WhichOneofArgType__verbose: _TypeAlias = _typing.Literal["_verbose", b"_verbose"]  # noqa: Y015
    _WhichOneofReturnType__warm_start: _TypeAlias = _typing.Literal["warm_start"]  # noqa: Y015
    _WhichOneofArgType__warm_start: _TypeAlias = _typing.Literal["_warm_start", b"_warm_start"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__adaptive_rho) -> _WhichOneofReturnType__adaptive_rho | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__adaptive_rho_fraction) -> _WhichOneofReturnType__adaptive_rho_fraction | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__adaptive_rho_interval) -> _WhichOneofReturnType__adaptive_rho_interval | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__adaptive_rho_tolerance) -> _WhichOneofReturnType__adaptive_rho_tolerance | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__alpha) -> _WhichOneofReturnType__alpha | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__check_termination) -> _WhichOneofReturnType__check_termination | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__delta) -> _WhichOneofReturnType__delta | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__eps_abs) -> _WhichOneofReturnType__eps_abs | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__eps_dual_inf) -> _WhichOneofReturnType__eps_dual_inf | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__eps_prim_inf) -> _WhichOneofReturnType__eps_prim_inf | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__eps_rel) -> _WhichOneofReturnType__eps_rel | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_iter) -> _WhichOneofReturnType__max_iter | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__polish) -> _WhichOneofReturnType__polish | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__polish_refine_iter) -> _WhichOneofReturnType__polish_refine_iter | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__rho) -> _WhichOneofReturnType__rho | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__scaled_termination) -> _WhichOneofReturnType__scaled_termination | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__scaling) -> _WhichOneofReturnType__scaling | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__sigma) -> _WhichOneofReturnType__sigma | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__time_limit) -> _WhichOneofReturnType__time_limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__verbose) -> _WhichOneofReturnType__verbose | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__warm_start) -> _WhichOneofReturnType__warm_start | None: ...

Global___OsqpSettingsProto: _TypeAlias = OsqpSettingsProto  # noqa: Y015

@_typing.final
class OsqpOutput(_message.Message):
    """Solver-specific output for OSQP."""

    DESCRIPTOR: _descriptor.Descriptor

    INITIALIZED_UNDERLYING_SOLVER_FIELD_NUMBER: _builtins.int
    initialized_underlying_solver: _builtins.bool
    """Field is true if the underlying OSQP++ object was initialized for the
    current solve, and false if the object was instead used incrementally. In
    more detail, this tracks: was osqp::OsqpSolver::Init called on the
    operations_research::math_opt::OsqpSolver::solver_ field at any point
    during the solve process?
    """
    def __init__(
        self,
        *,
        initialized_underlying_solver: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["initialized_underlying_solver", b"initialized_underlying_solver"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OsqpOutput: _TypeAlias = OsqpOutput  # noqa: Y015
