"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MultipleDimensionsBinPackingShape(_message.Message):
    """A Multiple Dimension BinPacking problem.
    It supports the following file format:
     - 2bp:
       see http://or.dei.unibo.it/library/two-dimensional-bin-packing-problem

    The generated problems have the following characteristics:

    You have identical boxes with n dimensions. The size of one box is stored in
    the field box_shape().
    You need to fit all items into the minimum number of boxes. Each item has the
    same number of dimensions and one or more possible shapes (this usually means
    that you can rotate the item).
    Each item must not overlap (in n dimensions) with any other item.

    The shape of one item. each edge is parallel to one axis of a dimension.
    One shape cannot be rotated, the item itself will contain multiple rotated
    shapes.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DIMENSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def dimensions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        dimensions: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dimensions", b"dimensions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MultipleDimensionsBinPackingShape: _TypeAlias = MultipleDimensionsBinPackingShape  # noqa: Y015

@_typing.final
class MultipleDimensionsBinPackingItem(_message.Message):
    """Items with multiple shapes often means that they can be rotated."""

    DESCRIPTOR: _descriptor.Descriptor

    SHAPES_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    """The value of the item (useful when solving the problem as a knapsack)."""
    @_builtins.property
    def shapes(self) -> _containers.RepeatedCompositeFieldContainer[Global___MultipleDimensionsBinPackingShape]:
        """All available shapes of the item."""

    def __init__(
        self,
        *,
        shapes: _abc.Iterable[Global___MultipleDimensionsBinPackingShape] | None = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["shapes", b"shapes", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MultipleDimensionsBinPackingItem: _TypeAlias = MultipleDimensionsBinPackingItem  # noqa: Y015

@_typing.final
class MultipleDimensionsBinPackingProblem(_message.Message):
    """The full problem: the enclosing box and the list of items."""

    DESCRIPTOR: _descriptor.Descriptor

    BOX_SHAPE_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def box_shape(self) -> Global___MultipleDimensionsBinPackingShape:
        """The enclosing shape."""

    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___MultipleDimensionsBinPackingItem]:
        """All available items of the problem."""

    def __init__(
        self,
        *,
        box_shape: Global___MultipleDimensionsBinPackingShape | None = ...,
        items: _abc.Iterable[Global___MultipleDimensionsBinPackingItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["box_shape", b"box_shape"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["box_shape", b"box_shape", "items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MultipleDimensionsBinPackingProblem: _TypeAlias = MultipleDimensionsBinPackingProblem  # noqa: Y015
