"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _CourseSchedulingResultStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CourseSchedulingResultStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CourseSchedulingResultStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    COURSE_SCHEDULING_RESULT_STATUS_UNSPECIFIED: _CourseSchedulingResultStatus.ValueType  # 0
    SOLVER_FEASIBLE: _CourseSchedulingResultStatus.ValueType  # 1
    """The solver had enough time to find some solution that satisfies all
    constraints, but it did not prove optimality (which means it may or may
    not have reached the optimal).

    This can happen for large LP models (linear programming), and is a frequent
    response for time-limited MIPs (mixed integer programming). This is also
    what the CP (constraint programming) solver will return if there is no
    objective specified.
    """
    SOLVER_OPTIMAL: _CourseSchedulingResultStatus.ValueType  # 2
    """The solver found the proven optimal solution."""
    SOLVER_INFEASIBLE: _CourseSchedulingResultStatus.ValueType  # 3
    """The model does not have any solution, according to the solver (which
    "proved" it, with the caveat that numerical proofs aren't actual proofs),
    or based on trivial considerations (eg. a variable whose lower bound is
    strictly greater than its upper bound).
    """
    SOLVER_MODEL_INVALID: _CourseSchedulingResultStatus.ValueType  # 4
    """Model errors. These are always deterministic and repeatable.
    They should be accompanied with a string description of the error.
    """
    SOLVER_NOT_SOLVED: _CourseSchedulingResultStatus.ValueType  # 5
    """The model has not been solved in the given time or the solver was not able
    to solve the model given.
    """
    ABNORMAL: _CourseSchedulingResultStatus.ValueType  # 6
    """An error (either numerical or from a bug in the code) occurred."""

class CourseSchedulingResultStatus(_CourseSchedulingResultStatus, metaclass=_CourseSchedulingResultStatusEnumTypeWrapper):
    """Status returned by the solver."""

COURSE_SCHEDULING_RESULT_STATUS_UNSPECIFIED: CourseSchedulingResultStatus.ValueType  # 0
SOLVER_FEASIBLE: CourseSchedulingResultStatus.ValueType  # 1
"""The solver had enough time to find some solution that satisfies all
constraints, but it did not prove optimality (which means it may or may
not have reached the optimal).

This can happen for large LP models (linear programming), and is a frequent
response for time-limited MIPs (mixed integer programming). This is also
what the CP (constraint programming) solver will return if there is no
objective specified.
"""
SOLVER_OPTIMAL: CourseSchedulingResultStatus.ValueType  # 2
"""The solver found the proven optimal solution."""
SOLVER_INFEASIBLE: CourseSchedulingResultStatus.ValueType  # 3
"""The model does not have any solution, according to the solver (which
"proved" it, with the caveat that numerical proofs aren't actual proofs),
or based on trivial considerations (eg. a variable whose lower bound is
strictly greater than its upper bound).
"""
SOLVER_MODEL_INVALID: CourseSchedulingResultStatus.ValueType  # 4
"""Model errors. These are always deterministic and repeatable.
They should be accompanied with a string description of the error.
"""
SOLVER_NOT_SOLVED: CourseSchedulingResultStatus.ValueType  # 5
"""The model has not been solved in the given time or the solver was not able
to solve the model given.
"""
ABNORMAL: CourseSchedulingResultStatus.ValueType  # 6
"""An error (either numerical or from a bug in the code) occurred."""
Global___CourseSchedulingResultStatus: _TypeAlias = CourseSchedulingResultStatus  # noqa: Y015

@_typing.final
class CourseSchedulingModel(_message.Message):
    """Information required to create a schedule for a school system."""

    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    DAYS_COUNT_FIELD_NUMBER: _builtins.int
    DAILY_TIME_SLOT_COUNT_FIELD_NUMBER: _builtins.int
    COURSES_FIELD_NUMBER: _builtins.int
    TEACHERS_FIELD_NUMBER: _builtins.int
    STUDENTS_FIELD_NUMBER: _builtins.int
    ROOMS_FIELD_NUMBER: _builtins.int
    display_name: _builtins.str
    """Schedule name, used only for logging purposes."""
    days_count: _builtins.int
    """The number of days in a schedule rotation. If the school system uses a
    block schedule, this value should be 1.
    """
    daily_time_slot_count: _builtins.int
    """The number of time slots each day in a schedule rotation. If the school
    system uses a block schedule, this value is the number of blocks.
    """
    @_builtins.property
    def courses(self) -> _containers.RepeatedCompositeFieldContainer[Global___Course]:
        """List of courses that need to be scheduled."""

    @_builtins.property
    def teachers(self) -> _containers.RepeatedCompositeFieldContainer[Global___Teacher]:
        """List of teachers."""

    @_builtins.property
    def students(self) -> _containers.RepeatedCompositeFieldContainer[Global___Student]:
        """List of students that need to be assigned to these courses."""

    @_builtins.property
    def rooms(self) -> _containers.RepeatedCompositeFieldContainer[Global___Room]:
        """List of rooms that the courses can be assigned to."""

    def __init__(
        self,
        *,
        display_name: _builtins.str = ...,
        days_count: _builtins.int = ...,
        daily_time_slot_count: _builtins.int = ...,
        courses: _abc.Iterable[Global___Course] | None = ...,
        teachers: _abc.Iterable[Global___Teacher] | None = ...,
        students: _abc.Iterable[Global___Student] | None = ...,
        rooms: _abc.Iterable[Global___Room] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["courses", b"courses", "daily_time_slot_count", b"daily_time_slot_count", "days_count", b"days_count", "display_name", b"display_name", "rooms", b"rooms", "students", b"students", "teachers", b"teachers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CourseSchedulingModel: _TypeAlias = CourseSchedulingModel  # noqa: Y015

@_typing.final
class CourseSchedulingResult(_message.Message):
    """Holds the solution to the course scheduling problem."""

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    SOLVER_STATUS_FIELD_NUMBER: _builtins.int
    CLASS_ASSIGNMENTS_FIELD_NUMBER: _builtins.int
    STUDENT_ASSIGNMENTS_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    """Human readable message about the solver or given model."""
    solver_status: Global___CourseSchedulingResultStatus.ValueType
    """Status of the solver."""
    @_builtins.property
    def class_assignments(self) -> _containers.RepeatedCompositeFieldContainer[Global___ClassAssignment]:
        """List of the time slot and room assignments for each section of a course."""

    @_builtins.property
    def student_assignments(self) -> _containers.RepeatedCompositeFieldContainer[Global___StudentAssignment]:
        """List of course and section assignments for each student."""

    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        solver_status: Global___CourseSchedulingResultStatus.ValueType = ...,
        class_assignments: _abc.Iterable[Global___ClassAssignment] | None = ...,
        student_assignments: _abc.Iterable[Global___StudentAssignment] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["class_assignments", b"class_assignments", "message", b"message", "solver_status", b"solver_status", "student_assignments", b"student_assignments"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CourseSchedulingResult: _TypeAlias = CourseSchedulingResult  # noqa: Y015

@_typing.final
class ClassAssignment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COURSE_INDEX_FIELD_NUMBER: _builtins.int
    SECTION_NUMBER_FIELD_NUMBER: _builtins.int
    TIME_SLOTS_FIELD_NUMBER: _builtins.int
    ROOM_INDICES_FIELD_NUMBER: _builtins.int
    course_index: _builtins.int
    """Index of the course in the CourseSchedulingModel."""
    section_number: _builtins.int
    """Specific section of the course in the CourseSchedulingModel."""
    @_builtins.property
    def time_slots(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Time slots that this class has been assigned to in the
        CourseSchedulingModel.
        """

    @_builtins.property
    def room_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Indices of the rooms that the class is assigned to in the
        CourseSchedulingModel. If this is not empty, then the number of indices
        must match the number of time slots.
        """

    def __init__(
        self,
        *,
        course_index: _builtins.int = ...,
        section_number: _builtins.int = ...,
        time_slots: _abc.Iterable[_builtins.int] | None = ...,
        room_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["course_index", b"course_index", "room_indices", b"room_indices", "section_number", b"section_number", "time_slots", b"time_slots"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ClassAssignment: _TypeAlias = ClassAssignment  # noqa: Y015

@_typing.final
class StudentAssignment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STUDENT_INDEX_FIELD_NUMBER: _builtins.int
    COURSE_INDICES_FIELD_NUMBER: _builtins.int
    SECTION_INDICES_FIELD_NUMBER: _builtins.int
    student_index: _builtins.int
    """Index of the student in the CourseSchedulingModel."""
    @_builtins.property
    def course_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Course indices in the CourseSchedulingModel that this student has been
        assigned to. The number of indices must match the number of section
        indices.
        """

    @_builtins.property
    def section_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Section indices for each Course in the CourseSchedulingModel this this
        student has been assigned to. The number of indices must match the number
        of course indices.
        """

    def __init__(
        self,
        *,
        student_index: _builtins.int = ...,
        course_indices: _abc.Iterable[_builtins.int] | None = ...,
        section_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["course_indices", b"course_indices", "section_indices", b"section_indices", "student_index", b"student_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StudentAssignment: _TypeAlias = StudentAssignment  # noqa: Y015

@_typing.final
class Course(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    MEETINGS_COUNT_FIELD_NUMBER: _builtins.int
    MAX_CAPACITY_FIELD_NUMBER: _builtins.int
    MIN_CAPACITY_FIELD_NUMBER: _builtins.int
    CONSECUTIVE_SLOTS_COUNT_FIELD_NUMBER: _builtins.int
    TEACHER_INDICES_FIELD_NUMBER: _builtins.int
    TEACHER_SECTION_COUNTS_FIELD_NUMBER: _builtins.int
    ROOM_INDICES_FIELD_NUMBER: _builtins.int
    display_name: _builtins.str
    """Course name, used only for logging purposes."""
    meetings_count: _builtins.int
    """The number of times each section of this course needs to meet during a
    schedule rotation. Each section of the course meets no more than once a
    day. If the school system uses a block schedule, then this value should
    be 1.
    """
    max_capacity: _builtins.int
    """The maximum number of students for this course. This value can be equal to
    +Infinity to encode a course has no maximum capacity.
    """
    min_capacity: _builtins.int
    """The minimum number of students for this course."""
    consecutive_slots_count: _builtins.int
    """The number of consecutive time slots that each section of this course needs
    to be scheduled for. This value can only be 1 or 2. If the value is 2, then
    2 consecutive time slots in a day counts as 1 meeting time for the section.
    """
    @_builtins.property
    def teacher_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """List of indices for the teachers of this course. We are assuming that each
        teacher teaches separately. Must have the same number of elements as the
        number of sections list.
        """

    @_builtins.property
    def teacher_section_counts(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The number of sections each teacher teaches of this course. Must have the
        same number of elements as the teacher index list.
        """

    @_builtins.property
    def room_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """List of the possible rooms that this course can be assigned to. This can
        be empty.
        """

    def __init__(
        self,
        *,
        display_name: _builtins.str = ...,
        meetings_count: _builtins.int = ...,
        max_capacity: _builtins.int = ...,
        min_capacity: _builtins.int = ...,
        consecutive_slots_count: _builtins.int = ...,
        teacher_indices: _abc.Iterable[_builtins.int] | None = ...,
        teacher_section_counts: _abc.Iterable[_builtins.int] | None = ...,
        room_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["consecutive_slots_count", b"consecutive_slots_count", "display_name", b"display_name", "max_capacity", b"max_capacity", "meetings_count", b"meetings_count", "min_capacity", b"min_capacity", "room_indices", b"room_indices", "teacher_indices", b"teacher_indices", "teacher_section_counts", b"teacher_section_counts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Course: _TypeAlias = Course  # noqa: Y015

@_typing.final
class Teacher(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    RESTRICTED_TIME_SLOTS_FIELD_NUMBER: _builtins.int
    display_name: _builtins.str
    """Teacher name, used only for logging purposes."""
    @_builtins.property
    def restricted_time_slots(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """List of time slots that the teacher cannot be scheduled for. These time
        slot values index to the accumulative number of time slots starting at 0.
        For example, if a schedule rotation has 5 days and 8 time slots per day,
        and a teacher cannot be scheduled for the last time slot of the fourth
        day, the number here would be 31.
        """

    def __init__(
        self,
        *,
        display_name: _builtins.str = ...,
        restricted_time_slots: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display_name", b"display_name", "restricted_time_slots", b"restricted_time_slots"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Teacher: _TypeAlias = Teacher  # noqa: Y015

@_typing.final
class Student(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    COURSE_INDICES_FIELD_NUMBER: _builtins.int
    display_name: _builtins.str
    """Student name, used only for logging purposes."""
    @_builtins.property
    def course_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """List of course indices that the student needs to be enrolled in."""

    def __init__(
        self,
        *,
        display_name: _builtins.str = ...,
        course_indices: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["course_indices", b"course_indices", "display_name", b"display_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Student: _TypeAlias = Student  # noqa: Y015

@_typing.final
class Room(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    CAPACITY_FIELD_NUMBER: _builtins.int
    display_name: _builtins.str
    """Room name, used only for logging purposes."""
    capacity: _builtins.int
    """Maximum number of students that can fit into this room."""
    def __init__(
        self,
        *,
        display_name: _builtins.str = ...,
        capacity: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capacity", b"capacity", "display_name", b"display_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Room: _TypeAlias = Room  # noqa: Y015
