"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
RCPSP: Resource-Constrained Project Scheduling Problem.

The problem description is as follows:

You have a set of resources. They all have a maximum capacity, and
can be renewable or not.

You have a set of tasks. Each task has a list of successors, and a
list of recipes. Each recipe consists of a duration, and a list of
demands, one per resource.
The problem is always built with 2 sentinels. The first task is the source
with a set of successors. The last task is the sink, with no successors and a
zero duration.
All tasks are reachable from the source task. And the sink task is reachable
from all tasks. Furthermore, the graph has no cycles.

The tasks dependencies form a DAG with a single source and a single end.
Both source and end tasks have a zero duration, and no resource consumption.

In case the problem is of type RCPSP/Max. The data contains an additional
3D array of delays per task. This structure contains the following
information for task i with recipe ri and successor j with recipe rj, then
start(i) + delay(i, ri, j, rj) <= start(j). This subsumes the normal
successor predecence of the non RCPSP/Max variation, i.e.:
  start(i) + duration(i, mi) <= start(j).

In the normal case, the objective is to minimize the makespan of the problem.

In the resource investment problem, there is no makespan. It is
replaced by a strict deadline, and each task must finish before
this deadline.  In that case, resources have a unit cost, and the
objective is to minimize the sum of resource cost.

In the consumer/producer case, tasks have a zero duration, and demands can be
negative. The constraint states that at each time point, the sum of demands
happening before or during this time must be between the min and max
capacity. Note that in that case, both min and max capacity can be negative.
Furthermore, if 0 is not in [min_capacity, max_capacity], then a sufficient
set of events must happen at time 0 such that the sum of their demands must
fall inside the capacity interval.

The supported file formats are:
  - standard psplib (.sm and .mm):
    http://www.om-db.wi.tum.de/psplib/data.html
  - rcpsp problem in the patterson format (.rcp):
    http://www.om-db.wi.tum.de/psplib/dataob.html
  - rcpsp/max (.sch):
    https://www.wiwi.tu-clausthal.de/de/abteilungen/produktion/forschung/
          schwerpunkte/project-generator/rcpspmax/
    https://www.wiwi.tu-clausthal.de/de/abteilungen/produktion/forschung/
          schwerpunkte/project-generator/mrcpspmax/
  - resource investment problem with max delay (.sch):
    https://www.wiwi.tu-clausthal.de/de/abteilungen/produktion/forschung/
          schwerpunkte/project-generator/ripmax/
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Resource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAX_CAPACITY_FIELD_NUMBER: _builtins.int
    MIN_CAPACITY_FIELD_NUMBER: _builtins.int
    RENEWABLE_FIELD_NUMBER: _builtins.int
    UNIT_COST_FIELD_NUMBER: _builtins.int
    max_capacity: _builtins.int
    """The max capacity of the cumulative."""
    min_capacity: _builtins.int
    """This field is used only in the consumer/producer case. It states the
    minimum capacity that must be valid at each time point.
    """
    renewable: _builtins.bool
    """Indicates if the resource is renewable, that is if a task demands
    d from this resource, then the available capacity decreases by d at the
    start of the task and increases by d at the end of the task.
    """
    unit_cost: _builtins.int
    """If non zero, then each unit of capacity will incur a cost of unit_cost."""
    def __init__(
        self,
        *,
        max_capacity: _builtins.int = ...,
        min_capacity: _builtins.int = ...,
        renewable: _builtins.bool = ...,
        unit_cost: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_capacity", b"max_capacity", "min_capacity", b"min_capacity", "renewable", b"renewable", "unit_cost", b"unit_cost"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Resource: _TypeAlias = Resource  # noqa: Y015

@_typing.final
class Recipe(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DURATION_FIELD_NUMBER: _builtins.int
    DEMANDS_FIELD_NUMBER: _builtins.int
    RESOURCES_FIELD_NUMBER: _builtins.int
    duration: _builtins.int
    """The duration of the task when this recipe is selected."""
    @_builtins.property
    def demands(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """In the general case, demand must be >= 0. In the consumer/producer case,
        it can be < 0. Note that in this case, the tasks always have a duration
        of zero. Thus the effect of the demand (increase or decrease of the
        current usage) happens at the start of the task.
        """

    @_builtins.property
    def resources(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """This parallel list indicates which resource index (in the main problem)
        the above demand corresponds to.
        """

    def __init__(
        self,
        *,
        duration: _builtins.int = ...,
        demands: _abc.Iterable[_builtins.int] | None = ...,
        resources: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["demands", b"demands", "duration", b"duration", "resources", b"resources"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Recipe: _TypeAlias = Recipe  # noqa: Y015

@_typing.final
class PerRecipeDelays(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MIN_DELAYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def min_delays(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        min_delays: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["min_delays", b"min_delays"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PerRecipeDelays: _TypeAlias = PerRecipeDelays  # noqa: Y015

@_typing.final
class PerSuccessorDelays(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECIPE_DELAYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def recipe_delays(self) -> _containers.RepeatedCompositeFieldContainer[Global___PerRecipeDelays]: ...
    def __init__(
        self,
        *,
        recipe_delays: _abc.Iterable[Global___PerRecipeDelays] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recipe_delays", b"recipe_delays"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PerSuccessorDelays: _TypeAlias = PerSuccessorDelays  # noqa: Y015

@_typing.final
class Task(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESSORS_FIELD_NUMBER: _builtins.int
    RECIPES_FIELD_NUMBER: _builtins.int
    SUCCESSOR_DELAYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def successors(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The indices of the successors tasks in the main problem."""

    @_builtins.property
    def recipes(self) -> _containers.RepeatedCompositeFieldContainer[Global___Recipe]:
        """The list of possible ways to execute the task."""

    @_builtins.property
    def successor_delays(self) -> _containers.RepeatedCompositeFieldContainer[Global___PerSuccessorDelays]:
        """If the current task has n successors and m recipes then this is
        an n x m matrix where each entry at line i is a vector with the
        same length as the number of recipes for the task successor[i]. If
        recipe m1 is chosen for the current task, and recipe m2 is chosen
        for its successor i, we have:
           start(current_task) + delay[i][m1][m2] <= start(successor_task).
        """

    def __init__(
        self,
        *,
        successors: _abc.Iterable[_builtins.int] | None = ...,
        recipes: _abc.Iterable[Global___Recipe] | None = ...,
        successor_delays: _abc.Iterable[Global___PerSuccessorDelays] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recipes", b"recipes", "successor_delays", b"successor_delays", "successors", b"successors"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Task: _TypeAlias = Task  # noqa: Y015

@_typing.final
class RcpspProblem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCES_FIELD_NUMBER: _builtins.int
    TASKS_FIELD_NUMBER: _builtins.int
    IS_CONSUMER_PRODUCER_FIELD_NUMBER: _builtins.int
    IS_RESOURCE_INVESTMENT_FIELD_NUMBER: _builtins.int
    IS_RCPSP_MAX_FIELD_NUMBER: _builtins.int
    DEADLINE_FIELD_NUMBER: _builtins.int
    HORIZON_FIELD_NUMBER: _builtins.int
    RELEASE_DATE_FIELD_NUMBER: _builtins.int
    TARDINESS_COST_FIELD_NUMBER: _builtins.int
    MPM_TIME_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    BASEDATA_FIELD_NUMBER: _builtins.int
    DUE_DATE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    is_consumer_producer: _builtins.bool
    """Problem type."""
    is_resource_investment: _builtins.bool
    is_rcpsp_max: _builtins.bool
    deadline: _builtins.int
    """If set, it defines a strict date, and each task must finish before this."""
    horizon: _builtins.int
    """Additional info stored in the source file.
    The horizon is a date where we are sure that all tasks can fit before it.
    """
    release_date: _builtins.int
    """The release date is defined in the rcpsp base format, but is not used."""
    tardiness_cost: _builtins.int
    """The tardiness cost is defined in the rcpsp base format, but is not used."""
    mpm_time: _builtins.int
    """The mpm_time is defined in the rcpsp base format, but is not used.
    It is defined as the minimum makespan in case of interruptible tasks.
    """
    seed: _builtins.int
    """Data used by the problem generator."""
    basedata: _builtins.str
    due_date: _builtins.int
    """The due date is defined in the rcpsp base format, but is not used."""
    name: _builtins.str
    @_builtins.property
    def resources(self) -> _containers.RepeatedCompositeFieldContainer[Global___Resource]:
        """Problem data."""

    @_builtins.property
    def tasks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Task]: ...
    def __init__(
        self,
        *,
        resources: _abc.Iterable[Global___Resource] | None = ...,
        tasks: _abc.Iterable[Global___Task] | None = ...,
        is_consumer_producer: _builtins.bool = ...,
        is_resource_investment: _builtins.bool = ...,
        is_rcpsp_max: _builtins.bool = ...,
        deadline: _builtins.int = ...,
        horizon: _builtins.int = ...,
        release_date: _builtins.int = ...,
        tardiness_cost: _builtins.int = ...,
        mpm_time: _builtins.int = ...,
        seed: _builtins.int = ...,
        basedata: _builtins.str = ...,
        due_date: _builtins.int = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["basedata", b"basedata", "deadline", b"deadline", "due_date", b"due_date", "horizon", b"horizon", "is_consumer_producer", b"is_consumer_producer", "is_rcpsp_max", b"is_rcpsp_max", "is_resource_investment", b"is_resource_investment", "mpm_time", b"mpm_time", "name", b"name", "release_date", b"release_date", "resources", b"resources", "seed", b"seed", "tardiness_cost", b"tardiness_cost", "tasks", b"tasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RcpspProblem: _TypeAlias = RcpspProblem  # noqa: Y015

@_typing.final
class RcpspAssignment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_OF_TASK_FIELD_NUMBER: _builtins.int
    SELECTED_RECIPE_OF_TASK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def start_of_task(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def selected_recipe_of_task(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        start_of_task: _abc.Iterable[_builtins.int] | None = ...,
        selected_recipe_of_task: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["selected_recipe_of_task", b"selected_recipe_of_task", "start_of_task", b"start_of_task"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RcpspAssignment: _TypeAlias = RcpspAssignment  # noqa: Y015
