"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ortools.util import int128_pb2 as _int128_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetCoverProto(_message.Message):
    """TODO(user): use uint64 instead of int32 for indices, as the solver
    supports it.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Subset(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COST_FIELD_NUMBER: _builtins.int
        ELEMENT_FIELD_NUMBER: _builtins.int
        cost: _builtins.float
        """The cost for using the given subset."""
        @_builtins.property
        def element(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
            """The list of elements in the subset."""

        def __init__(
            self,
            *,
            cost: _builtins.float | None = ...,
            element: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_cost", b"_cost", "cost", b"cost"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_cost", b"_cost", "cost", b"cost", "element", b"element"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__cost: _TypeAlias = _typing.Literal["cost"]  # noqa: Y015
        _WhichOneofArgType__cost: _TypeAlias = _typing.Literal["_cost", b"_cost"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__cost) -> _WhichOneofReturnType__cost | None: ...

    SUBSET_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    FINGERPRINT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """A user-defined name for the model."""
    @_builtins.property
    def subset(self) -> _containers.RepeatedCompositeFieldContainer[Global___SetCoverProto.Subset]:
        """The list of subsets in the model."""

    @_builtins.property
    def fingerprint(self) -> _int128_pb2.Int128:
        """An automatically fingerprint for the model. TODO(user): Implement."""

    def __init__(
        self,
        *,
        subset: _abc.Iterable[Global___SetCoverProto.Subset] | None = ...,
        name: _builtins.str | None = ...,
        fingerprint: _int128_pb2.Int128 | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_fingerprint", b"_fingerprint", "_name", b"_name", "fingerprint", b"fingerprint", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_fingerprint", b"_fingerprint", "_name", b"_name", "fingerprint", b"fingerprint", "name", b"name", "subset", b"subset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__fingerprint: _TypeAlias = _typing.Literal["fingerprint"]  # noqa: Y015
    _WhichOneofArgType__fingerprint: _TypeAlias = _typing.Literal["_fingerprint", b"_fingerprint"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__fingerprint) -> _WhichOneofReturnType__fingerprint | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___SetCoverProto: _TypeAlias = SetCoverProto  # noqa: Y015

@_typing.final
class SetCoverSolutionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SetCoverSolutionResponse._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNDEFINED: SetCoverSolutionResponse._Status.ValueType  # 0
        """Undefined."""
        OPTIMAL: SetCoverSolutionResponse._Status.ValueType  # 1
        """The solver found the proven optimal solution."""
        FEASIBLE: SetCoverSolutionResponse._Status.ValueType  # 2
        """The solver had enough time to find some solution that satisfied all
        constraints, but it did not reach the optimal.
        """
        INFEASIBLE: SetCoverSolutionResponse._Status.ValueType  # 3
        """The model does not have any solution."""
        INVALID: SetCoverSolutionResponse._Status.ValueType  # 4
        """The model is invalid."""

    class Status(_Status, metaclass=_StatusEnumTypeWrapper):
        """Result of the optimization."""

    UNDEFINED: SetCoverSolutionResponse.Status.ValueType  # 0
    """Undefined."""
    OPTIMAL: SetCoverSolutionResponse.Status.ValueType  # 1
    """The solver found the proven optimal solution."""
    FEASIBLE: SetCoverSolutionResponse.Status.ValueType  # 2
    """The solver had enough time to find some solution that satisfied all
    constraints, but it did not reach the optimal.
    """
    INFEASIBLE: SetCoverSolutionResponse.Status.ValueType  # 3
    """The model does not have any solution."""
    INVALID: SetCoverSolutionResponse.Status.ValueType  # 4
    """The model is invalid."""

    STATUS_FIELD_NUMBER: _builtins.int
    NUM_SUBSETS_FIELD_NUMBER: _builtins.int
    SUBSET_FIELD_NUMBER: _builtins.int
    COST_FIELD_NUMBER: _builtins.int
    COST_LOWER_BOUND_FIELD_NUMBER: _builtins.int
    FINGERPRINT_FIELD_NUMBER: _builtins.int
    MODEL_FINGERPRINT_FIELD_NUMBER: _builtins.int
    status: Global___SetCoverSolutionResponse.Status.ValueType
    """For future use. TODO(user): Implement."""
    num_subsets: _builtins.int
    """The number of subsets that are selected in the solution. This is used
    to decompress their indices below.
    """
    cost: _builtins.float
    """The cost of the solution, as computed by the algorithm."""
    cost_lower_bound: _builtins.float
    """A lower bound of the solution, as computed by the algorithm."""
    @_builtins.property
    def subset(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The list of the subsets selected in the solution."""

    @_builtins.property
    def fingerprint(self) -> _int128_pb2.Int128:
        """An automatically fingerprint for the solution. TODO(user): Implement."""

    @_builtins.property
    def model_fingerprint(self) -> _int128_pb2.Int128:
        """A reference to the model the solution applies to. TODO(user): Implement."""

    def __init__(
        self,
        *,
        status: Global___SetCoverSolutionResponse.Status.ValueType | None = ...,
        num_subsets: _builtins.int | None = ...,
        subset: _abc.Iterable[_builtins.int] | None = ...,
        cost: _builtins.float | None = ...,
        cost_lower_bound: _builtins.float | None = ...,
        fingerprint: _int128_pb2.Int128 | None = ...,
        model_fingerprint: _int128_pb2.Int128 | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_cost", b"_cost", "_cost_lower_bound", b"_cost_lower_bound", "_fingerprint", b"_fingerprint", "_model_fingerprint", b"_model_fingerprint", "_num_subsets", b"_num_subsets", "_status", b"_status", "cost", b"cost", "cost_lower_bound", b"cost_lower_bound", "fingerprint", b"fingerprint", "model_fingerprint", b"model_fingerprint", "num_subsets", b"num_subsets", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_cost", b"_cost", "_cost_lower_bound", b"_cost_lower_bound", "_fingerprint", b"_fingerprint", "_model_fingerprint", b"_model_fingerprint", "_num_subsets", b"_num_subsets", "_status", b"_status", "cost", b"cost", "cost_lower_bound", b"cost_lower_bound", "fingerprint", b"fingerprint", "model_fingerprint", b"model_fingerprint", "num_subsets", b"num_subsets", "status", b"status", "subset", b"subset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__cost: _TypeAlias = _typing.Literal["cost"]  # noqa: Y015
    _WhichOneofArgType__cost: _TypeAlias = _typing.Literal["_cost", b"_cost"]  # noqa: Y015
    _WhichOneofReturnType__cost_lower_bound: _TypeAlias = _typing.Literal["cost_lower_bound"]  # noqa: Y015
    _WhichOneofArgType__cost_lower_bound: _TypeAlias = _typing.Literal["_cost_lower_bound", b"_cost_lower_bound"]  # noqa: Y015
    _WhichOneofReturnType__fingerprint: _TypeAlias = _typing.Literal["fingerprint"]  # noqa: Y015
    _WhichOneofArgType__fingerprint: _TypeAlias = _typing.Literal["_fingerprint", b"_fingerprint"]  # noqa: Y015
    _WhichOneofReturnType__model_fingerprint: _TypeAlias = _typing.Literal["model_fingerprint"]  # noqa: Y015
    _WhichOneofArgType__model_fingerprint: _TypeAlias = _typing.Literal["_model_fingerprint", b"_model_fingerprint"]  # noqa: Y015
    _WhichOneofReturnType__num_subsets: _TypeAlias = _typing.Literal["num_subsets"]  # noqa: Y015
    _WhichOneofArgType__num_subsets: _TypeAlias = _typing.Literal["_num_subsets", b"_num_subsets"]  # noqa: Y015
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__cost) -> _WhichOneofReturnType__cost | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__cost_lower_bound) -> _WhichOneofReturnType__cost_lower_bound | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__fingerprint) -> _WhichOneofReturnType__fingerprint | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__model_fingerprint) -> _WhichOneofReturnType__model_fingerprint | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__num_subsets) -> _WhichOneofReturnType__num_subsets | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___SetCoverSolutionResponse: _TypeAlias = SetCoverSolutionResponse  # noqa: Y015
