"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol buffer to encode a Boolean satisfiability/optimization problem."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LinearBooleanConstraint(_message.Message):
    """A linear Boolean constraint which is a bounded sum of linear terms. Each term
    beeing a literal times an integer coefficient. If we assume that a literal
    takes the value 1 if it is true and 0 otherwise, the constraint is:
      lower_bound <= ... + coefficients[i] * literals[i] + ... <= upper_bound
    """

    DESCRIPTOR: _descriptor.Descriptor

    LITERALS_FIELD_NUMBER: _builtins.int
    COEFFICIENTS_FIELD_NUMBER: _builtins.int
    LOWER_BOUND_FIELD_NUMBER: _builtins.int
    UPPER_BOUND_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    lower_bound: _builtins.int
    """Optional lower (resp. upper) bound of the constraint. If not present, it
    means that the constraint is not bounded in this direction. The bounds
    are INCLUSIVE.
    """
    upper_bound: _builtins.int
    name: _builtins.str
    """The name of this constraint."""
    @_builtins.property
    def literals(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Linear terms involved in this constraint.

        literals[i] is the signed representation of the i-th literal of the
        constraint and coefficients[i] its coefficients. The signed representation
        is as follow: for a 0-based variable index x, (x + 1) represents the
        variable x and -(x + 1) represents its negation.

        Note that the same variable shouldn't appear twice and that zero
        coefficients are not allowed.
        """

    @_builtins.property
    def coefficients(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        literals: _abc.Iterable[_builtins.int] | None = ...,
        coefficients: _abc.Iterable[_builtins.int] | None = ...,
        lower_bound: _builtins.int | None = ...,
        upper_bound: _builtins.int | None = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lower_bound", b"lower_bound", "name", b"name", "upper_bound", b"upper_bound"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["coefficients", b"coefficients", "literals", b"literals", "lower_bound", b"lower_bound", "name", b"name", "upper_bound", b"upper_bound"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LinearBooleanConstraint: _TypeAlias = LinearBooleanConstraint  # noqa: Y015

@_typing.final
class LinearObjective(_message.Message):
    """The objective of an optimization problem."""

    DESCRIPTOR: _descriptor.Descriptor

    LITERALS_FIELD_NUMBER: _builtins.int
    COEFFICIENTS_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    SCALING_FACTOR_FIELD_NUMBER: _builtins.int
    offset: _builtins.float
    """For a given variable assignment, the "real" problem objective value is
    'scaling_factor * (minimization_objective + offset)' where
    'minimization_objective is the one defined just above.

    Note that this is not what we minimize, but it is what we display.
    In particular if scaling_factor is negative, then the "real" problem is
    a maximization problem, even if the "internal" objective is minimized.
    """
    scaling_factor: _builtins.float
    @_builtins.property
    def literals(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The goal is always to minimize the linear Boolean formula defined by these
        two fields: sum_i literal_i * coefficient_i where literal_i is 1 iff
        literal_i is true in a given assignment.

        Note that the same variable shouldn't appear twice and that zero
        coefficients are not allowed.
        """

    @_builtins.property
    def coefficients(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        literals: _abc.Iterable[_builtins.int] | None = ...,
        coefficients: _abc.Iterable[_builtins.int] | None = ...,
        offset: _builtins.float | None = ...,
        scaling_factor: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["offset", b"offset", "scaling_factor", b"scaling_factor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["coefficients", b"coefficients", "literals", b"literals", "offset", b"offset", "scaling_factor", b"scaling_factor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LinearObjective: _TypeAlias = LinearObjective  # noqa: Y015

@_typing.final
class BooleanAssignment(_message.Message):
    """Stores an assignment of variables as a list of true literals using their
    signed representation. There will be at most one literal per variable. The
    literals will be sorted by increasing variable index. The assignment may be
    partial in the sense that some variables may not appear and thus not be
    assigned.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LITERALS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def literals(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        literals: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["literals", b"literals"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BooleanAssignment: _TypeAlias = BooleanAssignment  # noqa: Y015

@_typing.final
class LinearBooleanProblem(_message.Message):
    """A linear Boolean problem."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    NUM_VARIABLES_FIELD_NUMBER: _builtins.int
    CONSTRAINTS_FIELD_NUMBER: _builtins.int
    OBJECTIVE_FIELD_NUMBER: _builtins.int
    VAR_NAMES_FIELD_NUMBER: _builtins.int
    ASSIGNMENT_FIELD_NUMBER: _builtins.int
    ORIGINAL_NUM_VARIABLES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The name of the problem."""
    num_variables: _builtins.int
    """The number of variables in the problem.
    All the signed representation of the problem literals must be in
    [-num_variables, num_variables], excluding 0.
    """
    original_num_variables: _builtins.int
    """Hack: When converting a wcnf formulat to a LinearBooleanProblem, extra
    variables need to be created. This stores the number of variables in the
    original problem (which are in one to one correspondence with the first
    variables of this problem).
    """
    @_builtins.property
    def constraints(self) -> _containers.RepeatedCompositeFieldContainer[Global___LinearBooleanConstraint]:
        """The constraints of the problem."""

    @_builtins.property
    def objective(self) -> Global___LinearObjective:
        """The objective of the problem.
        If left empty, we just have a satisfiability problem.
        """

    @_builtins.property
    def var_names(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The names of the problem variables. The variables index are 0-based and
        var_names[i] will be the name of the i-th variable which correspond to
        literals +(i + 1) or -(i + 1). This is optional and can be left empty.
        """

    @_builtins.property
    def assignment(self) -> Global___BooleanAssignment:
        """Stores an assignment of the problem variables. That may be an initial
        feasible solution, just a partial assignment or the optimal solution.
        """

    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
        num_variables: _builtins.int | None = ...,
        constraints: _abc.Iterable[Global___LinearBooleanConstraint] | None = ...,
        objective: Global___LinearObjective | None = ...,
        var_names: _abc.Iterable[_builtins.str] | None = ...,
        assignment: Global___BooleanAssignment | None = ...,
        original_num_variables: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["assignment", b"assignment", "name", b"name", "num_variables", b"num_variables", "objective", b"objective", "original_num_variables", b"original_num_variables"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["assignment", b"assignment", "constraints", b"constraints", "name", b"name", "num_variables", b"num_variables", "objective", b"objective", "original_num_variables", b"original_num_variables", "var_names", b"var_names"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LinearBooleanProblem: _TypeAlias = LinearBooleanProblem  # noqa: Y015
