"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from ortools.sat import cp_model_pb2 as _cp_model_pb2
from ortools.sat import sat_parameters_pb2 as _sat_parameters_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CpSolverRequest(_message.Message):
    """The request sent to the remote solve service."""

    DESCRIPTOR: _descriptor.Descriptor

    MODEL_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def model(self) -> _cp_model_pb2.CpModelProto:
        """The model to solve."""

    @_builtins.property
    def parameters(self) -> _sat_parameters_pb2.SatParameters:
        """Solver parameters."""

    def __init__(
        self,
        *,
        model: _cp_model_pb2.CpModelProto | None = ...,
        parameters: _sat_parameters_pb2.SatParameters | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["model", b"model", "parameters", b"parameters"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model", b"model", "parameters", b"parameters"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CpSolverRequest: _TypeAlias = CpSolverRequest  # noqa: Y015
