"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from ortools.service.v1.mathopt import model_parameters_pb2 as _model_parameters_pb2
from ortools.service.v1.mathopt import model_pb2 as _model_pb2
from ortools.service.v1.mathopt import parameters_pb2 as _parameters_pb2
from ortools.service.v1.mathopt import result_pb2 as _result_pb2
from ortools.service.v1.mathopt import solver_resources_pb2 as _solver_resources_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SolveMathOptModelRequest(_message.Message):
    """Request for a unary remote solve in MathOpt."""

    DESCRIPTOR: _descriptor.Descriptor

    SOLVER_TYPE_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    RESOURCES_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    MODEL_PARAMETERS_FIELD_NUMBER: _builtins.int
    solver_type: _parameters_pb2.SolverTypeProto.ValueType
    """Solver type to numerically solve the problem. Note that if a solver does
    not support a specific feature in the model, the optimization procedure
    won't be successful.
    """
    @_builtins.property
    def model(self) -> _model_pb2.ModelProto:
        """A mathematical representation of the optimization problem to solve."""

    @_builtins.property
    def resources(self) -> _solver_resources_pb2.SolverResourcesProto:
        """Hints on resources requested for the solve."""

    @_builtins.property
    def parameters(self) -> _parameters_pb2.SolveParametersProto:
        """Parameters to control a single solve. The enable_output parameter is
        handled specifically. For solvers that support messages callbacks, setting
        it to true will have the server register a message callback. The resulting
        messages will be returned in SolveMathOptModelResponse.messages. For other
        solvers, setting enable_output to true will result in an error.
        """

    @_builtins.property
    def model_parameters(self) -> _model_parameters_pb2.ModelSolveParametersProto:
        """Parameters to control a single solve that are specific to the input model
        (see SolveParametersProto for model independent parameters).
        """

    def __init__(
        self,
        *,
        solver_type: _parameters_pb2.SolverTypeProto.ValueType = ...,
        model: _model_pb2.ModelProto | None = ...,
        resources: _solver_resources_pb2.SolverResourcesProto | None = ...,
        parameters: _parameters_pb2.SolveParametersProto | None = ...,
        model_parameters: _model_parameters_pb2.ModelSolveParametersProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["model", b"model", "model_parameters", b"model_parameters", "parameters", b"parameters", "resources", b"resources"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model", b"model", "model_parameters", b"model_parameters", "parameters", b"parameters", "resources", b"resources", "solver_type", b"solver_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SolveMathOptModelRequest: _TypeAlias = SolveMathOptModelRequest  # noqa: Y015

@_typing.final
class SolveMathOptModelResponse(_message.Message):
    """Response for a unary remote solve in MathOpt."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULT_FIELD_NUMBER: _builtins.int
    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def result(self) -> _result_pb2.SolveResultProto:
        """Description of the output of solving the model in the request."""

    @_builtins.property
    def messages(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """If SolveParametersProto.enable_output has been used, this will contain log
        messages for solvers that support message callbacks.
        """

    def __init__(
        self,
        *,
        result: _result_pb2.SolveResultProto | None = ...,
        messages: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SolveMathOptModelResponse: _TypeAlias = SolveMathOptModelResponse  # noqa: Y015
