"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Solve parameters that are specific to the model."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from ortools.service.v1.mathopt import solution_pb2 as _solution_pb2
from ortools.service.v1.mathopt import sparse_containers_pb2 as _sparse_containers_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SolutionHintProto(_message.Message):
    """A suggested starting solution for the solver.

    MIP solvers generally only want primal information (`variable_values`), while
    LP solvers want both primal and dual information (`dual_values`).

    Many MIP solvers can work with: (1) partial solutions that do not specify all
    variables or (2) infeasible solutions. In these cases, solvers typically
    solve a sub-MIP to complete/correct the hint.

    How the hint is used by the solver, if at all, is highly dependent on the
    solver, the problem type, and the algorithm used. The most reliable way to
    ensure your hint has an effect is to read the underlying solvers logs with
    and without the hint.

    Simplex-based LP solvers typically prefer an initial basis to a solution hint
    (they need to crossover to convert the hint to a basic feasible solution
    otherwise).

    TODO(b/183616124): Add hint-priorities to variable_values.
    """

    DESCRIPTOR: _descriptor.Descriptor

    VARIABLE_VALUES_FIELD_NUMBER: _builtins.int
    DUAL_VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def variable_values(self) -> _sparse_containers_pb2.SparseDoubleVectorProto:
        """A possibly partial assignment of values to the primal variables of the
        problem. The solver-independent requirements for this sub-message are:
         * variable_values.ids are elements of VariablesProto.ids.
         * variable_values.values must all be finite.
        """

    @_builtins.property
    def dual_values(self) -> _sparse_containers_pb2.SparseDoubleVectorProto:
        """A (potentially partial) assignment of values to the linear constraints of
        the problem.

         Requirements:
          * dual_values.ids are elements of LinearConstraintsProto.ids.
          * dual_values.values must all be finite.
        """

    def __init__(
        self,
        *,
        variable_values: _sparse_containers_pb2.SparseDoubleVectorProto | None = ...,
        dual_values: _sparse_containers_pb2.SparseDoubleVectorProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dual_values", b"dual_values", "variable_values", b"variable_values"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dual_values", b"dual_values", "variable_values", b"variable_values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SolutionHintProto: _TypeAlias = SolutionHintProto  # noqa: Y015

@_typing.final
class ModelSolveParametersProto(_message.Message):
    """TODO(b/183628247): follow naming convention in fields below.
    Parameters to control a single solve that that are specific to the input
    model (see SolveParametersProto for model independent parameters).
    """

    DESCRIPTOR: _descriptor.Descriptor

    VARIABLE_VALUES_FILTER_FIELD_NUMBER: _builtins.int
    DUAL_VALUES_FILTER_FIELD_NUMBER: _builtins.int
    REDUCED_COSTS_FILTER_FIELD_NUMBER: _builtins.int
    INITIAL_BASIS_FIELD_NUMBER: _builtins.int
    SOLUTION_HINTS_FIELD_NUMBER: _builtins.int
    BRANCHING_PRIORITIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def variable_values_filter(self) -> _sparse_containers_pb2.SparseVectorFilterProto:
        """Filter that is applied to all returned sparse containers keyed by variables
        in PrimalSolutionProto and PrimalRayProto
        (PrimalSolutionProto.variable_values, PrimalRayProto.variable_values).

        Requirements:
         * filtered_ids are elements of VariablesProto.ids.
        """

    @_builtins.property
    def dual_values_filter(self) -> _sparse_containers_pb2.SparseVectorFilterProto:
        """Filter that is applied to all returned sparse containers keyed by linear
        constraints in DualSolutionProto and DualRay
        (DualSolutionProto.dual_values, DualRay.dual_values).

        Requirements:
         * filtered_ids are elements of LinearConstraints.ids.
        """

    @_builtins.property
    def reduced_costs_filter(self) -> _sparse_containers_pb2.SparseVectorFilterProto:
        """Filter that is applied to all returned sparse containers keyed by variables
        in DualSolutionProto and DualRay (DualSolutionProto.reduced_costs,
        DualRay.reduced_costs).

        Requirements:
         * filtered_ids are elements of VariablesProto.ids.
        """

    @_builtins.property
    def initial_basis(self) -> _solution_pb2.BasisProto:
        """Optional initial basis for warm starting simplex LP solvers. If set, it is
        expected to be valid according to `ValidateBasis` in
        `validators/solution_validator.h` for the current `ModelSummary`.
        """

    @_builtins.property
    def solution_hints(self) -> _containers.RepeatedCompositeFieldContainer[Global___SolutionHintProto]:
        """Optional solution hints. If the underlying solver only accepts a single
        hint, the first hint is used.
        """

    @_builtins.property
    def branching_priorities(self) -> _sparse_containers_pb2.SparseInt32VectorProto:
        """Optional branching priorities. Variables with higher values will be
        branched on first. Variables for which priorities are not set get the
        solver's default priority (usually zero).

        Requirements:
         * branching_priorities.values must be finite.
         * branching_priorities.ids must be elements of VariablesProto.ids.
        """

    def __init__(
        self,
        *,
        variable_values_filter: _sparse_containers_pb2.SparseVectorFilterProto | None = ...,
        dual_values_filter: _sparse_containers_pb2.SparseVectorFilterProto | None = ...,
        reduced_costs_filter: _sparse_containers_pb2.SparseVectorFilterProto | None = ...,
        initial_basis: _solution_pb2.BasisProto | None = ...,
        solution_hints: _abc.Iterable[Global___SolutionHintProto] | None = ...,
        branching_priorities: _sparse_containers_pb2.SparseInt32VectorProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["branching_priorities", b"branching_priorities", "dual_values_filter", b"dual_values_filter", "initial_basis", b"initial_basis", "reduced_costs_filter", b"reduced_costs_filter", "variable_values_filter", b"variable_values_filter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["branching_priorities", b"branching_priorities", "dual_values_filter", b"dual_values_filter", "initial_basis", b"initial_basis", "reduced_costs_filter", b"reduced_costs_filter", "solution_hints", b"solution_hints", "variable_values_filter", b"variable_values_filter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ModelSolveParametersProto: _TypeAlias = ModelSolveParametersProto  # noqa: Y015
