"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The suggested resources to solve an optimization problem."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SolverResourcesProto(_message.Message):
    """This message is used to specify some hints on the resources a remote solve is
    expected to use. These parameters are hints and may be ignored by the remote
    server (in particular in case of solve in a local subprocess, for example).

    When using SolveService.Solve and SolveService.ComputeInfeasibleSubsystem,
    these hints are mostly optional as some defaults will be computed based on
    the other parameters.

    When using SolveService.StreamSolve these hints are used to dimension the
    resources available during the execution of every action; thus it is
    recommended to set them.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CPU_FIELD_NUMBER: _builtins.int
    RAM_FIELD_NUMBER: _builtins.int
    cpu: _builtins.float
    """The number of CPUs this solve should be allocated (time-averaged over a
    short implementation-defined window). Must be finite and >=1.0.
    Note that if the SolveParametersProto.threads is not set then this
    parameter should also be left unset.
    """
    ram: _builtins.float
    """The limit of RAM for the solve in bytes. Must be finite and >=512000."""
    def __init__(
        self,
        *,
        cpu: _builtins.float | None = ...,
        ram: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_cpu", b"_cpu", "_ram", b"_ram", "cpu", b"cpu", "ram", b"ram"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_cpu", b"_cpu", "_ram", b"_ram", "cpu", b"cpu", "ram", b"ram"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__cpu: _TypeAlias = _typing.Literal["cpu"]  # noqa: Y015
    _WhichOneofArgType__cpu: _TypeAlias = _typing.Literal["_cpu", b"_cpu"]  # noqa: Y015
    _WhichOneofReturnType__ram: _TypeAlias = _typing.Literal["ram"]  # noqa: Y015
    _WhichOneofArgType__ram: _TypeAlias = _typing.Literal["_ram", b"_ram"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__cpu) -> _WhichOneofReturnType__cpu | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ram) -> _WhichOneofReturnType__ram | None: ...

Global___SolverResourcesProto: _TypeAlias = SolverResourcesProto  # noqa: Y015
