"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Messages for representing subsets of a models constraints, and for computing
infeasible subsystems of a model. Cf. "Irreducible Inconsistent subsystems"
(IIS), which are useful for debugging/diagnosing model infeasibility.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from ortools.math_opt import result_pb2 as _result_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ModelSubsetProto(_message.Message):
    """Represents a subset of the constraints (including variable bounds and
    integrality) of a `ModelProto`.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Bounds(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LOWER_FIELD_NUMBER: _builtins.int
        UPPER_FIELD_NUMBER: _builtins.int
        lower: _builtins.bool
        upper: _builtins.bool
        def __init__(
            self,
            *,
            lower: _builtins.bool = ...,
            upper: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["lower", b"lower", "upper", b"upper"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class VariableBoundsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___ModelSubsetProto.Bounds: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___ModelSubsetProto.Bounds | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LinearConstraintsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___ModelSubsetProto.Bounds: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___ModelSubsetProto.Bounds | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class QuadraticConstraintsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___ModelSubsetProto.Bounds: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___ModelSubsetProto.Bounds | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VARIABLE_BOUNDS_FIELD_NUMBER: _builtins.int
    VARIABLE_INTEGRALITY_FIELD_NUMBER: _builtins.int
    LINEAR_CONSTRAINTS_FIELD_NUMBER: _builtins.int
    QUADRATIC_CONSTRAINTS_FIELD_NUMBER: _builtins.int
    SECOND_ORDER_CONE_CONSTRAINTS_FIELD_NUMBER: _builtins.int
    SOS1_CONSTRAINTS_FIELD_NUMBER: _builtins.int
    SOS2_CONSTRAINTS_FIELD_NUMBER: _builtins.int
    INDICATOR_CONSTRAINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def variable_bounds(self) -> _containers.MessageMap[_builtins.int, Global___ModelSubsetProto.Bounds]:
        """Keys are variable IDs, and must be in [0, max(int64)). Values indicate
        which of the lower and upper variable bounds are included in the subsystem.
        """

    @_builtins.property
    def variable_integrality(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Variable IDs. Values must be in [0, max(int64)) and strictly increasing."""

    @_builtins.property
    def linear_constraints(self) -> _containers.MessageMap[_builtins.int, Global___ModelSubsetProto.Bounds]:
        """Keys are linear constraint IDs, and must be in [0, max(int64)). Values
        indicate which of the lower and upper bounds on the linear constraint are
        included in the subsystem.
        """

    @_builtins.property
    def quadratic_constraints(self) -> _containers.MessageMap[_builtins.int, Global___ModelSubsetProto.Bounds]:
        """Keys are quadratic constraint IDs, and must be in [0, max(int64)). Values
        indicate which of the lower and upper bounds on the quadratic constraint
        are included in the subsystem.
        """

    @_builtins.property
    def second_order_cone_constraints(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Second-order cone constraint IDs. Values must be in [0, max(int64)) and
        strictly increasing.
        """

    @_builtins.property
    def sos1_constraints(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """SOS1 constraint IDs. Values must be in [0, max(int64)) and strictly
        increasing.
        """

    @_builtins.property
    def sos2_constraints(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """SOS2 constraint IDs. Values must be in [0, max(int64)) and strictly
        increasing.
        """

    @_builtins.property
    def indicator_constraints(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Indicator constraint IDs. Values must be in [0, max(int64)) and strictly
        increasing.
        """

    def __init__(
        self,
        *,
        variable_bounds: _abc.Mapping[_builtins.int, Global___ModelSubsetProto.Bounds] | None = ...,
        variable_integrality: _abc.Iterable[_builtins.int] | None = ...,
        linear_constraints: _abc.Mapping[_builtins.int, Global___ModelSubsetProto.Bounds] | None = ...,
        quadratic_constraints: _abc.Mapping[_builtins.int, Global___ModelSubsetProto.Bounds] | None = ...,
        second_order_cone_constraints: _abc.Iterable[_builtins.int] | None = ...,
        sos1_constraints: _abc.Iterable[_builtins.int] | None = ...,
        sos2_constraints: _abc.Iterable[_builtins.int] | None = ...,
        indicator_constraints: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["indicator_constraints", b"indicator_constraints", "linear_constraints", b"linear_constraints", "quadratic_constraints", b"quadratic_constraints", "second_order_cone_constraints", b"second_order_cone_constraints", "sos1_constraints", b"sos1_constraints", "sos2_constraints", b"sos2_constraints", "variable_bounds", b"variable_bounds", "variable_integrality", b"variable_integrality"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ModelSubsetProto: _TypeAlias = ModelSubsetProto  # noqa: Y015

@_typing.final
class ComputeInfeasibleSubsystemResultProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEASIBILITY_FIELD_NUMBER: _builtins.int
    INFEASIBLE_SUBSYSTEM_FIELD_NUMBER: _builtins.int
    IS_MINIMAL_FIELD_NUMBER: _builtins.int
    feasibility: _result_pb2.FeasibilityStatusProto.ValueType
    """The primal feasibility status of the model, as determined by the solver."""
    is_minimal: _builtins.bool
    """True if the solver has certified that the returned subsystem is minimal
    (the instance is feasible if any additional constraint is removed). Note
    that, due to problem transformations MathOpt applies or idiosyncrasies of
    the solvers contract, the returned infeasible subsystem may not actually be
    minimal.
    """
    @_builtins.property
    def infeasible_subsystem(self) -> Global___ModelSubsetProto:
        """An infeasible subsystem of the input model. Set if `feasibility` is
        INFEASIBLE and empty otherwise. The IDs correspond to those constraints
        included in the infeasible subsystem. Submessages with `Bounds` values
        indicate which side of a potentially ranged constraint are included in the
        subsystem: lower bound, upper bound, or both.
        """

    def __init__(
        self,
        *,
        feasibility: _result_pb2.FeasibilityStatusProto.ValueType = ...,
        infeasible_subsystem: Global___ModelSubsetProto | None = ...,
        is_minimal: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["infeasible_subsystem", b"infeasible_subsystem"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feasibility", b"feasibility", "infeasible_subsystem", b"infeasible_subsystem", "is_minimal", b"is_minimal"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ComputeInfeasibleSubsystemResultProto: _TypeAlias = ComputeInfeasibleSubsystemResultProto  # noqa: Y015
