"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Data structures used throughout MathOpt to model sparse vectors and matrices.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SparseDoubleVectorProto(_message.Message):
    """A sparse representation of a vector of doubles."""

    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Must be sorted (in increasing ordering) with all elements distinct."""

    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Must have equal length to ids. May not contain NaN."""

    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
        values: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SparseDoubleVectorProto: _TypeAlias = SparseDoubleVectorProto  # noqa: Y015

@_typing.final
class SparseBoolVectorProto(_message.Message):
    """A sparse representation of a vector of bools."""

    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Should be sorted (in increasing ordering) with all elements distinct."""

    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]:
        """Must have equal length to ids."""

    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
        values: _abc.Iterable[_builtins.bool] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SparseBoolVectorProto: _TypeAlias = SparseBoolVectorProto  # noqa: Y015

@_typing.final
class SparseInt32VectorProto(_message.Message):
    """A sparse representation of a vector of ints."""

    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Should be sorted (in increasing ordering) with all elements distinct."""

    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Must have equal length to ids."""

    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
        values: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SparseInt32VectorProto: _TypeAlias = SparseInt32VectorProto  # noqa: Y015

@_typing.final
class SparseVectorFilterProto(_message.Message):
    """This message allows to query/set specific parts of a SparseXxxxVector.
    The default behavior is not to filter out anything.
    A common usage is to query only parts of solutions (only non-zero values,
    and/or just a hand-picked set of variable values).
    """

    DESCRIPTOR: _descriptor.Descriptor

    SKIP_ZERO_VALUES_FIELD_NUMBER: _builtins.int
    FILTER_BY_IDS_FIELD_NUMBER: _builtins.int
    FILTERED_IDS_FIELD_NUMBER: _builtins.int
    skip_zero_values: _builtins.bool
    """For SparseBoolVectorProto "zero" is `false`."""
    filter_by_ids: _builtins.bool
    """When true, return only the values corresponding to the IDs listed in
    filtered_ids.
    """
    @_builtins.property
    def filtered_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The list of IDs to use when filter_by_ids is true. Must be empty when
        filter_by_ids is false.
        NOTE: if this is empty, and filter_by_ids is true, you are saying that
        you do not want any information in the result.
        """

    def __init__(
        self,
        *,
        skip_zero_values: _builtins.bool = ...,
        filter_by_ids: _builtins.bool = ...,
        filtered_ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter_by_ids", b"filter_by_ids", "filtered_ids", b"filtered_ids", "skip_zero_values", b"skip_zero_values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SparseVectorFilterProto: _TypeAlias = SparseVectorFilterProto  # noqa: Y015

@_typing.final
class SparseDoubleMatrixProto(_message.Message):
    """A sparse representation of a matrix of doubles.

    The matrix is stored as triples of row id, column id, and coefficient. These
    three vectors must be of equal length. For all i, the tuple (row_ids[i],
    column_ids[i]) should be distinct. Entries must be in row major order.

    TODO(user): consider CSR.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ROW_IDS_FIELD_NUMBER: _builtins.int
    COLUMN_IDS_FIELD_NUMBER: _builtins.int
    COEFFICIENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def row_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def column_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def coefficients(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """May not contain NaN."""

    def __init__(
        self,
        *,
        row_ids: _abc.Iterable[_builtins.int] | None = ...,
        column_ids: _abc.Iterable[_builtins.int] | None = ...,
        coefficients: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["coefficients", b"coefficients", "column_ids", b"column_ids", "row_ids", b"row_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SparseDoubleMatrixProto: _TypeAlias = SparseDoubleMatrixProto  # noqa: Y015

@_typing.final
class LinearExpressionProto(_message.Message):
    """A sparse representation of a linear expression (a weighted sum of variables,
    plus a constant offset).
    """

    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    COEFFICIENTS_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    offset: _builtins.float
    """Must be finite and may not be NaN."""
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Ids of variables. Must be sorted (in increasing ordering) with all elements
        distinct.
        """

    @_builtins.property
    def coefficients(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Must have equal length to ids. Values must be finite may not be NaN."""

    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
        coefficients: _abc.Iterable[_builtins.float] | None = ...,
        offset: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["coefficients", b"coefficients", "ids", b"ids", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LinearExpressionProto: _TypeAlias = LinearExpressionProto  # noqa: Y015
