"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GScipParameters(_message.Message):
    """Contains both the "SCIP parameters" and gSCIP only configuration. For the
    SCIP parameters, the order of application is:
      1. Emphasis
      2. Meta parameters (heuristics, presolve, separating)
      3. Individual SCIP parameters (e.g. an entry in bool_params)
    Note that 1. and 2. both apply a combination of parameters from 3.

    For parameters that are marked as optional, the underlying solver default
    is used if they are not specified.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Emphasis:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EmphasisEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GScipParameters._Emphasis.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEFAULT_EMPHASIS: GScipParameters._Emphasis.ValueType  # 0
        COUNTER: GScipParameters._Emphasis.ValueType  # 1
        CP_SOLVER: GScipParameters._Emphasis.ValueType  # 2
        EASY_CIP: GScipParameters._Emphasis.ValueType  # 3
        FEASIBILITY: GScipParameters._Emphasis.ValueType  # 4
        HARD_LP: GScipParameters._Emphasis.ValueType  # 5
        OPTIMALITY: GScipParameters._Emphasis.ValueType  # 6
        PHASE_FEAS: GScipParameters._Emphasis.ValueType  # 7
        PHASE_IMPROVE: GScipParameters._Emphasis.ValueType  # 8
        PHASE_PROOF: GScipParameters._Emphasis.ValueType  # 9

    class Emphasis(_Emphasis, metaclass=_EmphasisEnumTypeWrapper):
        """See SCIP documentation for details:
        https://scip.zib.de/doc/html/type__paramset_8h.php#a2e51a867a8ea3ea16f15e7cc935c3f32
        """

    DEFAULT_EMPHASIS: GScipParameters.Emphasis.ValueType  # 0
    COUNTER: GScipParameters.Emphasis.ValueType  # 1
    CP_SOLVER: GScipParameters.Emphasis.ValueType  # 2
    EASY_CIP: GScipParameters.Emphasis.ValueType  # 3
    FEASIBILITY: GScipParameters.Emphasis.ValueType  # 4
    HARD_LP: GScipParameters.Emphasis.ValueType  # 5
    OPTIMALITY: GScipParameters.Emphasis.ValueType  # 6
    PHASE_FEAS: GScipParameters.Emphasis.ValueType  # 7
    PHASE_IMPROVE: GScipParameters.Emphasis.ValueType  # 8
    PHASE_PROOF: GScipParameters.Emphasis.ValueType  # 9

    class _MetaParamValue:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MetaParamValueEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GScipParameters._MetaParamValue.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEFAULT_META_PARAM_VALUE: GScipParameters._MetaParamValue.ValueType  # 0
        AGGRESSIVE: GScipParameters._MetaParamValue.ValueType  # 1
        FAST: GScipParameters._MetaParamValue.ValueType  # 2
        OFF: GScipParameters._MetaParamValue.ValueType  # 3

    class MetaParamValue(_MetaParamValue, metaclass=_MetaParamValueEnumTypeWrapper):
        """See SCIP documentation for details:
        https://scip.zib.de/doc/html/type__paramset_8h.php#a083067d8e425d0d44e834095e82902ed
        """

    DEFAULT_META_PARAM_VALUE: GScipParameters.MetaParamValue.ValueType  # 0
    AGGRESSIVE: GScipParameters.MetaParamValue.ValueType  # 1
    FAST: GScipParameters.MetaParamValue.ValueType  # 2
    OFF: GScipParameters.MetaParamValue.ValueType  # 3

    @_typing.final
    class BoolParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bool
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class IntParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LongParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RealParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.float
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.float = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CharParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StringParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    EMPHASIS_FIELD_NUMBER: _builtins.int
    HEURISTICS_FIELD_NUMBER: _builtins.int
    PRESOLVE_FIELD_NUMBER: _builtins.int
    SEPARATING_FIELD_NUMBER: _builtins.int
    BOOL_PARAMS_FIELD_NUMBER: _builtins.int
    INT_PARAMS_FIELD_NUMBER: _builtins.int
    LONG_PARAMS_FIELD_NUMBER: _builtins.int
    REAL_PARAMS_FIELD_NUMBER: _builtins.int
    CHAR_PARAMS_FIELD_NUMBER: _builtins.int
    STRING_PARAMS_FIELD_NUMBER: _builtins.int
    SILENCE_OUTPUT_FIELD_NUMBER: _builtins.int
    PRINT_DETAILED_SOLVING_STATS_FIELD_NUMBER: _builtins.int
    PRINT_SCIP_MODEL_FIELD_NUMBER: _builtins.int
    SEARCH_LOGS_FILENAME_FIELD_NUMBER: _builtins.int
    DETAILED_SOLVING_STATS_FILENAME_FIELD_NUMBER: _builtins.int
    SCIP_MODEL_FILENAME_FIELD_NUMBER: _builtins.int
    NUM_SOLUTIONS_FIELD_NUMBER: _builtins.int
    OBJECTIVE_LIMIT_FIELD_NUMBER: _builtins.int
    emphasis: Global___GScipParameters.Emphasis.ValueType
    heuristics: Global___GScipParameters.MetaParamValue.ValueType
    """See SCIPsetHeuristics() for details:
    https://scip.zib.de/doc/html/group__ParameterMethods.php#gaeccb7859066cadd01d0df7aca98e2c7d
    """
    presolve: Global___GScipParameters.MetaParamValue.ValueType
    """See SCIPsetPresolving() for details:
    https://scip.zib.de/doc/html/group__ParameterMethods.php#ga8365de8ab5ec5961c005e2d77965b182
    """
    separating: Global___GScipParameters.MetaParamValue.ValueType
    """See SCIPsetSeparating() for details:
    https://scip.zib.de/doc/html/group__ParameterMethods.php#gad0c64e3e9b8def72fd8a7d3d9dce7729
    """
    silence_output: _builtins.bool
    """///////////////////////////////////////////////////////////////////////////
    gSCIP only parameters
    ///////////////////////////////////////////////////////////////////////////

    Disable all terminal output (override all logging parameters). To control
    only the search logs, see also the SCIP parameter display/verblevel and
    from gscip_parameters.h, SetLogLevel() and SetOutputEnabled().
    """
    print_detailed_solving_stats: _builtins.bool
    """Log solver metrics to terminal when finished solving (unless silenced)."""
    print_scip_model: _builtins.bool
    """Write out the model in SCIP's text format before solving to the terminal
    (unless silenced).
    """
    search_logs_filename: _builtins.str
    """If nonempty, search logs are written here INSTEAD OF out to terminal. See
    also the SCIP parameter display/verblevel and from gscip_parameters.h, the
    functions SetLogLevel() and SetOutputEnabled() for configuring the search
    logs.

    Does not use gfile, can only write to local disk.
    """
    detailed_solving_stats_filename: _builtins.str
    """If non-empty, write detailed_solving_stats to a file. Can be set
    independently from print_detailed_solving_stats.

    Does not use gfile, can only write to local disk.
    """
    scip_model_filename: _builtins.str
    """If nonempty, out the model in SCIP's text format to a file before solving.
    Can be set independently of print_scip_model.

    Does not use gfile, can only write to local disk.
    """
    num_solutions: _builtins.int
    """How many solutions to retrieve from the solution pool (if this many exist).
    At least one solution will always be returned, even if num_solutions < 1.
    """
    objective_limit: _builtins.float
    """If set, ignore all solutions worse than objective_limit, for details see
    SCIPsetObjlimit(). Note that the solution pool will still contain solutions
    worse than the limit as SCIP uses these to run improvement heuristics, and
    if you query all solutions at the end of the solve they will be present,
    even if you found no solution that met the limit and returned infeasible.
    """
    @_builtins.property
    def bool_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.bool]:
        """See https://scip.zib.de/doc/html/PARAMETERS.php for a list of all SCIP
        parameters.
        """

    @_builtins.property
    def int_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]: ...
    @_builtins.property
    def long_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]: ...
    @_builtins.property
    def real_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.float]: ...
    @_builtins.property
    def char_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def string_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        emphasis: Global___GScipParameters.Emphasis.ValueType = ...,
        heuristics: Global___GScipParameters.MetaParamValue.ValueType | None = ...,
        presolve: Global___GScipParameters.MetaParamValue.ValueType | None = ...,
        separating: Global___GScipParameters.MetaParamValue.ValueType | None = ...,
        bool_params: _abc.Mapping[_builtins.str, _builtins.bool] | None = ...,
        int_params: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
        long_params: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
        real_params: _abc.Mapping[_builtins.str, _builtins.float] | None = ...,
        char_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        string_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        silence_output: _builtins.bool | None = ...,
        print_detailed_solving_stats: _builtins.bool = ...,
        print_scip_model: _builtins.bool = ...,
        search_logs_filename: _builtins.str = ...,
        detailed_solving_stats_filename: _builtins.str = ...,
        scip_model_filename: _builtins.str = ...,
        num_solutions: _builtins.int | None = ...,
        objective_limit: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_heuristics", b"_heuristics", "_num_solutions", b"_num_solutions", "_objective_limit", b"_objective_limit", "_presolve", b"_presolve", "_separating", b"_separating", "_silence_output", b"_silence_output", "heuristics", b"heuristics", "num_solutions", b"num_solutions", "objective_limit", b"objective_limit", "presolve", b"presolve", "separating", b"separating", "silence_output", b"silence_output"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_heuristics", b"_heuristics", "_num_solutions", b"_num_solutions", "_objective_limit", b"_objective_limit", "_presolve", b"_presolve", "_separating", b"_separating", "_silence_output", b"_silence_output", "bool_params", b"bool_params", "char_params", b"char_params", "detailed_solving_stats_filename", b"detailed_solving_stats_filename", "emphasis", b"emphasis", "heuristics", b"heuristics", "int_params", b"int_params", "long_params", b"long_params", "num_solutions", b"num_solutions", "objective_limit", b"objective_limit", "presolve", b"presolve", "print_detailed_solving_stats", b"print_detailed_solving_stats", "print_scip_model", b"print_scip_model", "real_params", b"real_params", "scip_model_filename", b"scip_model_filename", "search_logs_filename", b"search_logs_filename", "separating", b"separating", "silence_output", b"silence_output", "string_params", b"string_params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__heuristics: _TypeAlias = _typing.Literal["heuristics"]  # noqa: Y015
    _WhichOneofArgType__heuristics: _TypeAlias = _typing.Literal["_heuristics", b"_heuristics"]  # noqa: Y015
    _WhichOneofReturnType__num_solutions: _TypeAlias = _typing.Literal["num_solutions"]  # noqa: Y015
    _WhichOneofArgType__num_solutions: _TypeAlias = _typing.Literal["_num_solutions", b"_num_solutions"]  # noqa: Y015
    _WhichOneofReturnType__objective_limit: _TypeAlias = _typing.Literal["objective_limit"]  # noqa: Y015
    _WhichOneofArgType__objective_limit: _TypeAlias = _typing.Literal["_objective_limit", b"_objective_limit"]  # noqa: Y015
    _WhichOneofReturnType__presolve: _TypeAlias = _typing.Literal["presolve"]  # noqa: Y015
    _WhichOneofArgType__presolve: _TypeAlias = _typing.Literal["_presolve", b"_presolve"]  # noqa: Y015
    _WhichOneofReturnType__separating: _TypeAlias = _typing.Literal["separating"]  # noqa: Y015
    _WhichOneofArgType__separating: _TypeAlias = _typing.Literal["_separating", b"_separating"]  # noqa: Y015
    _WhichOneofReturnType__silence_output: _TypeAlias = _typing.Literal["silence_output"]  # noqa: Y015
    _WhichOneofArgType__silence_output: _TypeAlias = _typing.Literal["_silence_output", b"_silence_output"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__heuristics) -> _WhichOneofReturnType__heuristics | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__num_solutions) -> _WhichOneofReturnType__num_solutions | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__objective_limit) -> _WhichOneofReturnType__objective_limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__presolve) -> _WhichOneofReturnType__presolve | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__separating) -> _WhichOneofReturnType__separating | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__silence_output) -> _WhichOneofReturnType__silence_output | None: ...

Global___GScipParameters: _TypeAlias = GScipParameters  # noqa: Y015

@_typing.final
class GScipSolvingStats(_message.Message):
    """TODO(user): this should be machine generated by script and contain all of
    https://scip.zib.de/doc/html/group__PublicSolvingStatsMethods.php
    """

    DESCRIPTOR: _descriptor.Descriptor

    BEST_OBJECTIVE_FIELD_NUMBER: _builtins.int
    BEST_BOUND_FIELD_NUMBER: _builtins.int
    PRIMAL_SIMPLEX_ITERATIONS_FIELD_NUMBER: _builtins.int
    DUAL_SIMPLEX_ITERATIONS_FIELD_NUMBER: _builtins.int
    BARRIER_ITERATIONS_FIELD_NUMBER: _builtins.int
    TOTAL_LP_ITERATIONS_FIELD_NUMBER: _builtins.int
    NODE_COUNT_FIELD_NUMBER: _builtins.int
    FIRST_LP_RELAXATION_BOUND_FIELD_NUMBER: _builtins.int
    ROOT_NODE_BOUND_FIELD_NUMBER: _builtins.int
    DETERMINISTIC_TIME_FIELD_NUMBER: _builtins.int
    best_objective: _builtins.float
    """The objective value of the best solution (or the cutoff). If no solution is
    found, returns +inf for minimization and -inf for maximization. Equivalent
    to SCIPgetPrimalbound().
    """
    best_bound: _builtins.float
    """The best proven bound on the object (e.g. through the LP relaxation).
    Returns +inf for maximization and -inf for minimization if no bound was
    found. Equivalent to SCIPgetDualBound().
    """
    primal_simplex_iterations: _builtins.int
    """nprimallpiterations in SCIP. The number of primal simplex LP iterations."""
    dual_simplex_iterations: _builtins.int
    """nduallpiterations in SCIP. The number of dual simplex LP iterations."""
    barrier_iterations: _builtins.int
    """nbarrierlpiterations. The number of barrier LP iterations."""
    total_lp_iterations: _builtins.int
    """nlp_iterations in SCIP. The total number of LP steps taken. Note that this
    number be at least (and often strictly greater than)
    primal_simplex_iterations + dual simplex iterations + barrier iterations,
    as it includes other types of iterations (e.g. see ndivinglpiterations).
    """
    node_count: _builtins.int
    """NTotalNodes in SCIP.
    This is the total number of nodes used in the solve, potentially across
    multiple branch-and-bound trees. Use limits/totalnodes (rather than
    limits/nodes) to control this value.
    """
    first_lp_relaxation_bound: _builtins.float
    """FirstLPDualboundRoot in SCIP. The bound obtained from the first LP solve
    at the root node.
    """
    root_node_bound: _builtins.float
    """DualboundRoot in SCIP. The bound obtained at the root node, possibly after
    multiple rounds of cuts.
    """
    deterministic_time: _builtins.float
    """A deterministic measure of work done during the solve. The units of this
    field are specific to SCIP.
    """
    def __init__(
        self,
        *,
        best_objective: _builtins.float = ...,
        best_bound: _builtins.float = ...,
        primal_simplex_iterations: _builtins.int = ...,
        dual_simplex_iterations: _builtins.int = ...,
        barrier_iterations: _builtins.int = ...,
        total_lp_iterations: _builtins.int = ...,
        node_count: _builtins.int = ...,
        first_lp_relaxation_bound: _builtins.float = ...,
        root_node_bound: _builtins.float = ...,
        deterministic_time: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["barrier_iterations", b"barrier_iterations", "best_bound", b"best_bound", "best_objective", b"best_objective", "deterministic_time", b"deterministic_time", "dual_simplex_iterations", b"dual_simplex_iterations", "first_lp_relaxation_bound", b"first_lp_relaxation_bound", "node_count", b"node_count", "primal_simplex_iterations", b"primal_simplex_iterations", "root_node_bound", b"root_node_bound", "total_lp_iterations", b"total_lp_iterations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GScipSolvingStats: _TypeAlias = GScipSolvingStats  # noqa: Y015

@_typing.final
class GScipOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GScipOutput._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: GScipOutput._Status.ValueType  # 0
        USER_INTERRUPT: GScipOutput._Status.ValueType  # 1
        NODE_LIMIT: GScipOutput._Status.ValueType  # 2
        TOTAL_NODE_LIMIT: GScipOutput._Status.ValueType  # 3
        STALL_NODE_LIMIT: GScipOutput._Status.ValueType  # 4
        TIME_LIMIT: GScipOutput._Status.ValueType  # 5
        MEM_LIMIT: GScipOutput._Status.ValueType  # 6
        GAP_LIMIT: GScipOutput._Status.ValueType  # 7
        SOL_LIMIT: GScipOutput._Status.ValueType  # 8
        BEST_SOL_LIMIT: GScipOutput._Status.ValueType  # 9
        RESTART_LIMIT: GScipOutput._Status.ValueType  # 10
        OPTIMAL: GScipOutput._Status.ValueType  # 11
        INFEASIBLE: GScipOutput._Status.ValueType  # 12
        UNBOUNDED: GScipOutput._Status.ValueType  # 13
        INF_OR_UNBD: GScipOutput._Status.ValueType  # 14
        TERMINATE: GScipOutput._Status.ValueType  # 15
        INVALID_SOLVER_PARAMETERS: GScipOutput._Status.ValueType  # 16
        """WARNING(rander): we add some extra status values beyond SCIP here"""

    class Status(_Status, metaclass=_StatusEnumTypeWrapper):
        """See https://scip.zib.de/doc/html/type__stat_8h.php"""

    UNKNOWN: GScipOutput.Status.ValueType  # 0
    USER_INTERRUPT: GScipOutput.Status.ValueType  # 1
    NODE_LIMIT: GScipOutput.Status.ValueType  # 2
    TOTAL_NODE_LIMIT: GScipOutput.Status.ValueType  # 3
    STALL_NODE_LIMIT: GScipOutput.Status.ValueType  # 4
    TIME_LIMIT: GScipOutput.Status.ValueType  # 5
    MEM_LIMIT: GScipOutput.Status.ValueType  # 6
    GAP_LIMIT: GScipOutput.Status.ValueType  # 7
    SOL_LIMIT: GScipOutput.Status.ValueType  # 8
    BEST_SOL_LIMIT: GScipOutput.Status.ValueType  # 9
    RESTART_LIMIT: GScipOutput.Status.ValueType  # 10
    OPTIMAL: GScipOutput.Status.ValueType  # 11
    INFEASIBLE: GScipOutput.Status.ValueType  # 12
    UNBOUNDED: GScipOutput.Status.ValueType  # 13
    INF_OR_UNBD: GScipOutput.Status.ValueType  # 14
    TERMINATE: GScipOutput.Status.ValueType  # 15
    INVALID_SOLVER_PARAMETERS: GScipOutput.Status.ValueType  # 16
    """WARNING(rander): we add some extra status values beyond SCIP here"""

    STATUS_FIELD_NUMBER: _builtins.int
    STATUS_DETAIL_FIELD_NUMBER: _builtins.int
    STATS_FIELD_NUMBER: _builtins.int
    status: Global___GScipOutput.Status.ValueType
    status_detail: _builtins.str
    @_builtins.property
    def stats(self) -> Global___GScipSolvingStats: ...
    def __init__(
        self,
        *,
        status: Global___GScipOutput.Status.ValueType = ...,
        status_detail: _builtins.str = ...,
        stats: Global___GScipSolvingStats | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats", "status", b"status", "status_detail", b"status_detail"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GScipOutput: _TypeAlias = GScipOutput  # noqa: Y015
