"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2010-2025 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class IntVarAssignment(_message.Message):
    """Storage for IntVars."""

    DESCRIPTOR: _descriptor.Descriptor

    VAR_ID_FIELD_NUMBER: _builtins.int
    MIN_FIELD_NUMBER: _builtins.int
    MAX_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    var_id: _builtins.str
    min: _builtins.int
    max: _builtins.int
    active: _builtins.bool
    def __init__(
        self,
        *,
        var_id: _builtins.str = ...,
        min: _builtins.int = ...,
        max: _builtins.int = ...,
        active: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "max", b"max", "min", b"min", "var_id", b"var_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IntVarAssignment: _TypeAlias = IntVarAssignment  # noqa: Y015

@_typing.final
class IntervalVarAssignment(_message.Message):
    """Storage for IntervalVars."""

    DESCRIPTOR: _descriptor.Descriptor

    VAR_ID_FIELD_NUMBER: _builtins.int
    START_MIN_FIELD_NUMBER: _builtins.int
    START_MAX_FIELD_NUMBER: _builtins.int
    DURATION_MIN_FIELD_NUMBER: _builtins.int
    DURATION_MAX_FIELD_NUMBER: _builtins.int
    END_MIN_FIELD_NUMBER: _builtins.int
    END_MAX_FIELD_NUMBER: _builtins.int
    PERFORMED_MIN_FIELD_NUMBER: _builtins.int
    PERFORMED_MAX_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    var_id: _builtins.str
    start_min: _builtins.int
    start_max: _builtins.int
    duration_min: _builtins.int
    duration_max: _builtins.int
    end_min: _builtins.int
    end_max: _builtins.int
    performed_min: _builtins.int
    performed_max: _builtins.int
    active: _builtins.bool
    def __init__(
        self,
        *,
        var_id: _builtins.str = ...,
        start_min: _builtins.int = ...,
        start_max: _builtins.int = ...,
        duration_min: _builtins.int = ...,
        duration_max: _builtins.int = ...,
        end_min: _builtins.int = ...,
        end_max: _builtins.int = ...,
        performed_min: _builtins.int = ...,
        performed_max: _builtins.int = ...,
        active: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "duration_max", b"duration_max", "duration_min", b"duration_min", "end_max", b"end_max", "end_min", b"end_min", "performed_max", b"performed_max", "performed_min", b"performed_min", "start_max", b"start_max", "start_min", b"start_min", "var_id", b"var_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IntervalVarAssignment: _TypeAlias = IntervalVarAssignment  # noqa: Y015

@_typing.final
class SequenceVarAssignment(_message.Message):
    """Storage for SequenceVars."""

    DESCRIPTOR: _descriptor.Descriptor

    VAR_ID_FIELD_NUMBER: _builtins.int
    FORWARD_SEQUENCE_FIELD_NUMBER: _builtins.int
    BACKWARD_SEQUENCE_FIELD_NUMBER: _builtins.int
    UNPERFORMED_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    var_id: _builtins.str
    active: _builtins.bool
    @_builtins.property
    def forward_sequence(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def backward_sequence(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def unperformed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        var_id: _builtins.str = ...,
        forward_sequence: _abc.Iterable[_builtins.int] | None = ...,
        backward_sequence: _abc.Iterable[_builtins.int] | None = ...,
        unperformed: _abc.Iterable[_builtins.int] | None = ...,
        active: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "backward_sequence", b"backward_sequence", "forward_sequence", b"forward_sequence", "unperformed", b"unperformed", "var_id", b"var_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SequenceVarAssignment: _TypeAlias = SequenceVarAssignment  # noqa: Y015

@_typing.final
class WorkerInfo(_message.Message):
    """This message indicates how the assignment was produced."""

    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    BNS_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.int
    bns: _builtins.str
    def __init__(
        self,
        *,
        worker_id: _builtins.int = ...,
        bns: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bns", b"bns", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WorkerInfo: _TypeAlias = WorkerInfo  # noqa: Y015

@_typing.final
class AssignmentProto(_message.Message):
    """Global container for all assignment variables and objective"""

    DESCRIPTOR: _descriptor.Descriptor

    INT_VAR_ASSIGNMENT_FIELD_NUMBER: _builtins.int
    INTERVAL_VAR_ASSIGNMENT_FIELD_NUMBER: _builtins.int
    SEQUENCE_VAR_ASSIGNMENT_FIELD_NUMBER: _builtins.int
    OBJECTIVE_FIELD_NUMBER: _builtins.int
    WORKER_INFO_FIELD_NUMBER: _builtins.int
    IS_VALID_FIELD_NUMBER: _builtins.int
    is_valid: _builtins.bool
    @_builtins.property
    def int_var_assignment(self) -> _containers.RepeatedCompositeFieldContainer[Global___IntVarAssignment]: ...
    @_builtins.property
    def interval_var_assignment(self) -> _containers.RepeatedCompositeFieldContainer[Global___IntervalVarAssignment]: ...
    @_builtins.property
    def sequence_var_assignment(self) -> _containers.RepeatedCompositeFieldContainer[Global___SequenceVarAssignment]: ...
    @_builtins.property
    def objective(self) -> _containers.RepeatedCompositeFieldContainer[Global___IntVarAssignment]: ...
    @_builtins.property
    def worker_info(self) -> Global___WorkerInfo: ...
    def __init__(
        self,
        *,
        int_var_assignment: _abc.Iterable[Global___IntVarAssignment] | None = ...,
        interval_var_assignment: _abc.Iterable[Global___IntervalVarAssignment] | None = ...,
        sequence_var_assignment: _abc.Iterable[Global___SequenceVarAssignment] | None = ...,
        objective: _abc.Iterable[Global___IntVarAssignment] | None = ...,
        worker_info: Global___WorkerInfo | None = ...,
        is_valid: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["worker_info", b"worker_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["int_var_assignment", b"int_var_assignment", "interval_var_assignment", b"interval_var_assignment", "is_valid", b"is_valid", "objective", b"objective", "sequence_var_assignment", b"sequence_var_assignment", "worker_info", b"worker_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AssignmentProto: _TypeAlias = AssignmentProto  # noqa: Y015
