"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This file contains a protocol buffer definition for search limits.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RegularLimitParameters(_message.Message):
    """A search limit
    The default values for int64 fields is the maxima value, i.e., 2^63-1
    """

    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    BRANCHES_FIELD_NUMBER: _builtins.int
    FAILURES_FIELD_NUMBER: _builtins.int
    SOLUTIONS_FIELD_NUMBER: _builtins.int
    SMART_TIME_CHECK_FIELD_NUMBER: _builtins.int
    CUMULATIVE_FIELD_NUMBER: _builtins.int
    time: _builtins.int
    """TODO(user): Specify the time units or switch to google.Duration proto."""
    branches: _builtins.int
    failures: _builtins.int
    solutions: _builtins.int
    smart_time_check: _builtins.bool
    cumulative: _builtins.bool
    def __init__(
        self,
        *,
        time: _builtins.int = ...,
        branches: _builtins.int = ...,
        failures: _builtins.int = ...,
        solutions: _builtins.int = ...,
        smart_time_check: _builtins.bool = ...,
        cumulative: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["branches", b"branches", "cumulative", b"cumulative", "failures", b"failures", "smart_time_check", b"smart_time_check", "solutions", b"solutions", "time", b"time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RegularLimitParameters: _TypeAlias = RegularLimitParameters  # noqa: Y015
