"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol buffer used to store search statistics."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LocalSearchStatistics(_message.Message):
    """Statistics on local search."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FirstSolutionStatistics(_message.Message):
        """First solution statistics collected during search."""

        DESCRIPTOR: _descriptor.Descriptor

        STRATEGY_FIELD_NUMBER: _builtins.int
        DURATION_SECONDS_FIELD_NUMBER: _builtins.int
        strategy: _builtins.str
        """Name of the strategy used."""
        duration_seconds: _builtins.float
        """Time spent in the decision builder."""
        def __init__(
            self,
            *,
            strategy: _builtins.str = ...,
            duration_seconds: _builtins.float = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_seconds", b"duration_seconds", "strategy", b"strategy"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LocalSearchOperatorStatistics(_message.Message):
        """Statistics on local search operators called during the search."""

        DESCRIPTOR: _descriptor.Descriptor

        LOCAL_SEARCH_OPERATOR_FIELD_NUMBER: _builtins.int
        NUM_NEIGHBORS_FIELD_NUMBER: _builtins.int
        NUM_FILTERED_NEIGHBORS_FIELD_NUMBER: _builtins.int
        NUM_ACCEPTED_NEIGHBORS_FIELD_NUMBER: _builtins.int
        DURATION_SECONDS_FIELD_NUMBER: _builtins.int
        MAKE_NEXT_NEIGHBOR_DURATION_SECONDS_FIELD_NUMBER: _builtins.int
        ACCEPT_NEIGHBOR_DURATION_SECONDS_FIELD_NUMBER: _builtins.int
        local_search_operator: _builtins.str
        """Name of the operator."""
        num_neighbors: _builtins.int
        """Number of neighbors generated by the operator."""
        num_filtered_neighbors: _builtins.int
        """Number of neighbors which were filtered."""
        num_accepted_neighbors: _builtins.int
        """Number of neighbors eventually accepted."""
        duration_seconds: _builtins.float
        """Time spent in the operator."""
        make_next_neighbor_duration_seconds: _builtins.float
        """Time spent in creating neighbors (calling MakeNextNeighbor)."""
        accept_neighbor_duration_seconds: _builtins.float
        """Time spent in accepting a neighbor (restoration and storage, not
        including filtering).
        """
        def __init__(
            self,
            *,
            local_search_operator: _builtins.str = ...,
            num_neighbors: _builtins.int = ...,
            num_filtered_neighbors: _builtins.int = ...,
            num_accepted_neighbors: _builtins.int = ...,
            duration_seconds: _builtins.float = ...,
            make_next_neighbor_duration_seconds: _builtins.float = ...,
            accept_neighbor_duration_seconds: _builtins.float = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["accept_neighbor_duration_seconds", b"accept_neighbor_duration_seconds", "duration_seconds", b"duration_seconds", "local_search_operator", b"local_search_operator", "make_next_neighbor_duration_seconds", b"make_next_neighbor_duration_seconds", "num_accepted_neighbors", b"num_accepted_neighbors", "num_filtered_neighbors", b"num_filtered_neighbors", "num_neighbors", b"num_neighbors"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LocalSearchFilterStatistics(_message.Message):
        """Statistics on local search filters called during the search."""

        DESCRIPTOR: _descriptor.Descriptor

        LOCAL_SEARCH_FILTER_FIELD_NUMBER: _builtins.int
        NUM_CALLS_FIELD_NUMBER: _builtins.int
        NUM_REJECTS_FIELD_NUMBER: _builtins.int
        DURATION_SECONDS_FIELD_NUMBER: _builtins.int
        NUM_REJECTS_PER_SECOND_FIELD_NUMBER: _builtins.int
        CONTEXT_FIELD_NUMBER: _builtins.int
        local_search_filter: _builtins.str
        """Name of the filter."""
        num_calls: _builtins.int
        """Number of times the filter was called."""
        num_rejects: _builtins.int
        """Number of times the filter rejected a neighbor."""
        duration_seconds: _builtins.float
        """Time spent in the filter."""
        num_rejects_per_second: _builtins.float
        """Number of rejects per second."""
        context: _builtins.str
        """Context within which the filter was called."""
        def __init__(
            self,
            *,
            local_search_filter: _builtins.str = ...,
            num_calls: _builtins.int = ...,
            num_rejects: _builtins.int = ...,
            duration_seconds: _builtins.float = ...,
            num_rejects_per_second: _builtins.float = ...,
            context: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "duration_seconds", b"duration_seconds", "local_search_filter", b"local_search_filter", "num_calls", b"num_calls", "num_rejects", b"num_rejects", "num_rejects_per_second", b"num_rejects_per_second"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    FIRST_SOLUTION_STATISTICS_FIELD_NUMBER: _builtins.int
    LOCAL_SEARCH_OPERATOR_STATISTICS_FIELD_NUMBER: _builtins.int
    TOTAL_NUM_NEIGHBORS_FIELD_NUMBER: _builtins.int
    TOTAL_NUM_FILTERED_NEIGHBORS_FIELD_NUMBER: _builtins.int
    TOTAL_NUM_ACCEPTED_NEIGHBORS_FIELD_NUMBER: _builtins.int
    LOCAL_SEARCH_FILTER_STATISTICS_FIELD_NUMBER: _builtins.int
    total_num_neighbors: _builtins.int
    """Total number of (filtered/accepted) neighbors created during the search."""
    total_num_filtered_neighbors: _builtins.int
    total_num_accepted_neighbors: _builtins.int
    @_builtins.property
    def first_solution_statistics(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocalSearchStatistics.FirstSolutionStatistics]:
        """Statistics for each first solution called during the search."""

    @_builtins.property
    def local_search_operator_statistics(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocalSearchStatistics.LocalSearchOperatorStatistics]:
        """Statistics for each operator called during the search."""

    @_builtins.property
    def local_search_filter_statistics(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocalSearchStatistics.LocalSearchFilterStatistics]:
        """Statistics for each filter called during the search."""

    def __init__(
        self,
        *,
        first_solution_statistics: _abc.Iterable[Global___LocalSearchStatistics.FirstSolutionStatistics] | None = ...,
        local_search_operator_statistics: _abc.Iterable[Global___LocalSearchStatistics.LocalSearchOperatorStatistics] | None = ...,
        total_num_neighbors: _builtins.int = ...,
        total_num_filtered_neighbors: _builtins.int = ...,
        total_num_accepted_neighbors: _builtins.int = ...,
        local_search_filter_statistics: _abc.Iterable[Global___LocalSearchStatistics.LocalSearchFilterStatistics] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["first_solution_statistics", b"first_solution_statistics", "local_search_filter_statistics", b"local_search_filter_statistics", "local_search_operator_statistics", b"local_search_operator_statistics", "total_num_accepted_neighbors", b"total_num_accepted_neighbors", "total_num_filtered_neighbors", b"total_num_filtered_neighbors", "total_num_neighbors", b"total_num_neighbors"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalSearchStatistics: _TypeAlias = LocalSearchStatistics  # noqa: Y015

@_typing.final
class ConstraintSolverStatistics(_message.Message):
    """Statistics on the search in the constraint solver."""

    DESCRIPTOR: _descriptor.Descriptor

    NUM_BRANCHES_FIELD_NUMBER: _builtins.int
    NUM_FAILURES_FIELD_NUMBER: _builtins.int
    NUM_SOLUTIONS_FIELD_NUMBER: _builtins.int
    BYTES_USED_FIELD_NUMBER: _builtins.int
    DURATION_SECONDS_FIELD_NUMBER: _builtins.int
    num_branches: _builtins.int
    """Number of branches explored."""
    num_failures: _builtins.int
    """Number of failures/backtracks."""
    num_solutions: _builtins.int
    """Number of solutions found."""
    bytes_used: _builtins.int
    """Memory usage of the solver."""
    duration_seconds: _builtins.float
    """Total time spent in the solver."""
    def __init__(
        self,
        *,
        num_branches: _builtins.int = ...,
        num_failures: _builtins.int = ...,
        num_solutions: _builtins.int = ...,
        bytes_used: _builtins.int = ...,
        duration_seconds: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_used", b"bytes_used", "duration_seconds", b"duration_seconds", "num_branches", b"num_branches", "num_failures", b"num_failures", "num_solutions", b"num_solutions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConstraintSolverStatistics: _TypeAlias = ConstraintSolverStatistics  # noqa: Y015

@_typing.final
class SearchStatistics(_message.Message):
    """Search statistics."""

    DESCRIPTOR: _descriptor.Descriptor

    LOCAL_SEARCH_STATISTICS_FIELD_NUMBER: _builtins.int
    CONSTRAINT_SOLVER_STATISTICS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def local_search_statistics(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocalSearchStatistics]:
        """Local search statistics for each solver context."""

    @_builtins.property
    def constraint_solver_statistics(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConstraintSolverStatistics]:
        """Constraint solver statistics."""

    def __init__(
        self,
        *,
        local_search_statistics: _abc.Iterable[Global___LocalSearchStatistics] | None = ...,
        constraint_solver_statistics: _abc.Iterable[Global___ConstraintSolverStatistics] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["constraint_solver_statistics", b"constraint_solver_statistics", "local_search_statistics", b"local_search_statistics"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchStatistics: _TypeAlias = SearchStatistics  # noqa: Y015
